### PR TITLE
Add ONE-TIME or SUBSCRIPTION to Donation model's string description.

### LINKED ISSUE #194: change donation str() to indicate in admin view one-off or periodic
;-)

### PR DESCRIPTION
**Pull request by Shriukan33**
Closes #194

### CODE REVIEW

**Comment by Shriukan33** [comment]
Closed, why no merge ?

**Comment by JeffAbrahamson** [comment]
Is the commit perhaps already on master by rebase?

**Comment by Shriukan33** [comment]
It is indeed

**Comment by JeffAbrahamson** [comment]
;-)

**Pull request closed without merging**
