### PR TITLE
Benja fix report flag display

### PR DESCRIPTION
**Pull request by Shriukan33**
Fix bug discovered in #996 

Changes :
* Dropdown is not empty anymore when you are the sessio's author
* Text color is back to its original color in the modal (used to be white on white because of #990 )

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
PR's are a github construct.  So are issues, but commits typically flag them.

So your commit comment,
```
╭╴ ((204da43...) $%)╶╮
╰ jeff@morning:transport_nantes $ git log -1 --stat
commit 204da433bdecb8b6abcf9c8a0012c2a3f4299f69 (HEAD, origin/benja-fix-report-flag-display)
Author: Benjamin Mourgues <benjamin@mobilitains.fr>
Date:   Tue Nov 15 10:26:34 2022 +0100

    Fix mobilito session report modal to display properly
    
    In PR #990 we changed mobilito's color scheme and this form
    has been left behind. Text is now readable.
    
    Aside, the case where the user that loads the page is the session's
    author wasn't properly handled, the dropdown was empty.

 transport_nantes/mobilito/static/mobilito/css/mobilito.css                 | 3 +++
 transport_nantes/mobilito/templates/mobilito/mobilito_session_summary.html | 6 +++++-
 2 files changed, 8 insertions(+), 1 deletion(-)
╭╴ ((204da43...) $%)╶╮
╰ jeff@morning:transport_nantes $
```

So commands like `git log --grep` won't find anything.

Commits are tagged to issues because that's what you're working on.  The PR is about review and approval and is not as interesting in history.  So it's appropriate that we tag commits with issues and not PRs.

**Comment by JeffAbrahamson** [comment]
This needs an issue (a bug was reported, that requires creating an issue), and the commit comment should then tag that issue.

The description of what changed should be clearer: "to display properly" provides no context, doesn't describe the bug or the fix at all.

The colour change belongs in a different commit.  Moreover, it's a strange summary: report a bug on the dropdown malfunctioning and present a PR about a colour change with, by the by, a fix to a real functionality problem.  Could you please separate these two?

PR #990 closed issue #964, which has 8 commits (according to `git log --grep`).  The colour change which fixes a minor bug on #964 can simply tag #964.  If it were more significant, we'd of course want to create an issue and tag the new issue.

**Comment by Shriukan33** [comment]
Thanks for feedback

**Review by JeffAbrahamson — APPROVED** [review]
LGTM.

**Pull request merged**
