### PR TITLE
Revert change on list style

### PR DESCRIPTION
**Pull request by Shriukan33**
Revert back to enabled the list styles.
This change was too rigid and difficult to use.

Part of #336

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
I'm not sure that commit comment is understandable without today's context.

The commit content looks fine, of course.

**Comment by Shriukan33** [comment]
Reworded the commit, don't know how to put it any better, suggestions welcome

**Comment by JeffAbrahamson** [comment]
Yeah, fine.

Better, if you want, would be to think,
* why did we do this?
* what do we lose by undoing it?
* what do we gain by undoing it?

That's the sort of context one would want when looking at it six months later.  It's the context we don't really have looking at the commit message from six months ago.

**Comment by JeffAbrahamson** [comment]
Yeah, fine.

Better, if you want, would be to think,
* why did we do this?
* what do we lose by undoing it?
* what do we gain by undoing it?

That's the sort of context one would want when looking at it six months later.  It's the context we don't really have looking at the commit message from six months ago.

**Comment by JeffAbrahamson** [comment]
LGTM

**Pull request merged**
