### PR TITLE
Benja mobilito based jeff 3

### PR DESCRIPTION
**Pull request by Shriukan33**
This PR merges benja-mobilito-v2 with jeff-mobilito-3

It notably adds :
- the address form (which is optional) before the recording session
- The user agent in the session model
- Fixes for the recording page and logs.

This branch has been deployed on beta the 19th of July.

### CODE REVIEW

**Review by JeffAbrahamson — COMMENTED** [review]
LGTM except:
* Ideally, but possibly in a new commit, we should say user_agent and not user_browser
* I'm fine with the email having draft content, but saying WIP in the commit message screams "do not merge".  If you just mean that the content isn't final, then just say that: Send email after finishing recording session.  Email content is rudimentary for initial user testing and needs work."  Or something similar.
* "You can trigger it" -- generally, avoid second person in commit messages, it reads weird.  And sometimes the person will think "_I_ can't", which sort of falsifies your statement.

**Comment by JeffAbrahamson** [comment]
What is status on this PR going into the weekend?

**Comment by JeffAbrahamson** [comment]
Who is this waiting for?

**Comment by Shriukan33** [comment]
Still on the firefox bug, have been busy with templates on other parts of the site lately

**Comment by Shriukan33** [comment]
Firefox bug sorted

**Review by JeffAbrahamson — APPROVED** [review]
LGTM.

**Pull request merged**
