### PR TITLE
New password reset

### PR DESCRIPTION
**Pull request by Qlexio**
Well, I removed code from settings but `transport_nantes.urls` is well modified. There is nothing left in it about password reset and I changed nothing else.

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Please stop sending PRs with style errors.  If this were a rare instance, I'd probably shrug and ignore it.  But this is the rule, not the exception, so I really need to push back, even if it's not the most important issue.

```
╭╴ (donation-85 $%=) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ git diff 45f626d..260ad5e | grep -E '\s+$'
+  
+		    Nous vous avons envoyé un mél d'instructions pour réinitialiser votre mot de passe. 
+Veuillez cliquer sur le lien ci-dessous pour lancer la procédure de réinitialisation de mot de passe 
+	<button class="btn btn-lg btn-primary btn-block" type="submit">Envoyer le mail</button>  
 
+    
+        
+        
 
 
 
 
 
 
+    
╭╴ (donation-85 $%=) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ 
```

**Comment by Qlexio** [comment]
@JeffAbrahamson I don't have the empty lines you show me when I do the same git diff

**Comment by JeffAbrahamson** [comment]
That's not possible unless your commits have different SHA1's than mine.

What happens when you execute the line I did above?

**Comment by Qlexio** [comment]
@JeffAbrahamson 
I don't know why the git + grep command didn't work yesterday but I made it run this morning.
I have rebased the branch to squash useless commit then pushed it again.
You can watch the branch `origin/new_password_reset`

**Comment by JeffAbrahamson** [comment]
Please demonstrate why you believe this is ready for me to review.

Hint:

```
╭╴ (donation-85 *+$%=)╶╮
╰ jeff@birdsong:tn_web $ git-log-table origin/new_password_reset -4
b5a66e0|2020-12-17|Alexandre BENARD| (origin/new_password_reset) Remove dev EMAIL_BACKEND from settings
b344499|2020-12-15|Alexandre BENARD| Add password reset
893dee1|2020-12-11|Alexandre BENARD| Add password reset form
5bd62da|2020-12-17|Jeff Abrahamson| Create and use the tag url_don
╭╴ (donation-85 *+$%=)╶╮
╰ jeff@birdsong:tn_web $ git diff 5bd62da..b5a66e0 | sed -Ee 's/\s+$/<<--<<--<<--<<--<<--<<--/;' | grep '<<--<<' | wc -l
5
╭╴ (donation-85 *+$%=)╶╮
╰ jeff@birdsong:tn_web $ 


```

**Comment by Qlexio** [comment]
@JeffAbrahamson 
Actually, I have to check for that website pages are responsive.
And probably need to do a rebase before pushing again.

**Comment by Qlexio** [comment]
@JeffAbrahamson 
Well,
1. Rebase has been done
2. Templates are responsive
3. Test passes
Branch has been push under `origin/new_password_reset`

**Comment by JeffAbrahamson** [comment]
Your branch history still shows changes to settings.py, even if you later undo them.  This is sloppy.  As an error, it's acceptable to slide mistakenly into the master branch.  As part of a code review, it's not.  I don't really understand why this is still an issue.

Do you understand that you waste developer time when you ask for code review without bring prepared, when you ask questions that you haven't prepared.  This is as much true with colleagues as on SO.  Wasting time is ok, we all do it, and we try to get better.  But there's a more pernicious effect, which is that in repetition you lose credibility.

For example, my code reviews at this point stop with the first error that was in the last review.

```
╭╴ (master *+$%=) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ git log --stat 59e5a2c..origin/new_password_reset | grep settings
    Remove dev EMAIL_BACKEND from settings
    * Remove "dev" condition from settings.py about EMAIL_BACKEND
 transport_nantes/transport_nantes/settings.py      | 14 +++----
    * Add condition in settings.py for sending of password reset mail in
 transport_nantes/transport_nantes/settings.py      | 14 ++++---
╭╴ (master *+$%=) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ 
```

**Comment by Qlexio** [comment]
I am not sure to well understand the last message from you @JeffAbrahamson 
So, canyou translate it in french please?

**Pull request closed without merging**
