### PR TITLE
Remove immutable status of slug field in TopicBlog Item

### PR DESCRIPTION
**Pull request by mcmikashi**
Add a warning if the slug field  change

If this is good i will do the same on other TB

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
On saving form with modified slug, this happens:
image

**Comment by JeffAbrahamson** [comment]
Otherwise, generally looks good.  The js feedback is not quite perfect, in that modifying the slug and then going back to unmodified is not quite the same as not modifying.  For example, it warns me about how many items there are.  Either fix now (if it's easy) or make an issue to remember to fix later (if it will take a few hours).

**Comment by mcmikashi** [comment]
> On saving form with modified slug, this happens: image

I dont have this error  the slug you used was "go!" ?

**Comment by mcmikashi** [comment]
> For example, it warns me about how many items there are

This is not the same file, did you want to hide this if it was the previous slug ?

**Comment by mcmikashi** [comment]
- Update the logic

**Comment by JeffAbrahamson** [comment]
Please fix your spelling in `edit_slug_warning.js`: s/warnning/warning/;

**Comment by JeffAbrahamson** [comment]
LGTM.

**Pull request merged**
