### PR TITLE
Add warning before send

### PR DESCRIPTION
**Pull request by Shriukan33**
based on #563 

Add a confirmation window before sending a TBEmail to a mailing list.

It informs you about how many people are subscribed to a mailing list, and makes an extra step to prevent accidental sending.

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Wouldn't it make more sense to display the number of recipients from the outset rather than waiting for the user to hit the send button?  You can still have a chicken box, but providing information up front is usually a better experience.  It satisfies the condition of least surprise, for example.

**Comment by JeffAbrahamson** [comment]
Otherwise, LGTM.

Note that this is based on a branch that isn't yet approved.

**Comment by Shriukan33** [comment]
Added a small line under the dropdown, informing you about the number of recipients : 
image

**Comment by JeffAbrahamson** [comment]
In ab3af08b, it's somewhere between weird and wrong to have function calls that are lateral in the inheritance tree.  If there is commonality like this, it should be refactored to a base class.

Indeed, you'll need this function for all four TB* subclasses, might it not be easier to write them all at once so that you see what's common all at the same time?  Sorting all of these together should be quite fast, I'd think.

**Comment by JeffAbrahamson** [comment]
5a5feda4 - LGTM

**Comment by JeffAbrahamson** [comment]
97983cf1 - A bit of an aside, but to be usable, this is going to have to be async.  But that doesn't matter when we have no one subscribed.

**Comment by Shriukan33** [comment]
> 97983cf1 - A bit of an aside, but to be usable, this is going to have to be async. But that doesn't matter when we have no one subscribed.

Weirdly your commit shas aren't parsed by GitHub but I think I know what you're talking about, just not sure. 
What's not async here ?

**Comment by JeffAbrahamson** [comment]
97983cf1 - I think the logic in `get_number_of_recipients()` could be improved.  Why wait until the use clicks send in order to provide feedback?

This is a conversation we have often.  _Before_ the user acts, make sure, if possible, that you present the user with all the information s/he needs to make an informed decision.  If you still want a chicken box, that's fine, but don't surprise the user with its contents.

So when the user chooses the list from the dropdown, that's the time to fetch and display the number of recipients.

**Comment by Shriukan33** [comment]
> 97983cf1 - I think the logic in `get_number_of_recipients()` could be improved. Why wait until the use clicks send in order to provide feedback?
> 
> This is a conversation we have often. _Before_ the user acts, make sure, if possible, that you present the user with all the information s/he needs to make an informed decision. If you still want a chicken box, that's fine, but don't surprise the user with its contents.
> 
> So when the user chooses the list from the dropdown, that's the time to fetch and display the number of recipients.

This is not what's happening, did you fetch the branch ?
I made it so the number of recipients is shown when you select a mailing list, even before you click send.

**Comment by JeffAbrahamson** [comment]
> > 97983cf1 - I think the logic in `get_number_of_recipients()` could be improved. Why wait until the use clicks send in order to provide feedback?
> > This is a conversation we have often. _Before_ the user acts, make sure, if possible, that you present the user with all the information s/he needs to make an informed decision. If you still want a chicken box, that's fine, but don't surprise the user with its contents.
> > So when the user chooses the list from the dropdown, that's the time to fetch and display the number of recipients.
> 
> This is not what's happening, did you fetch the branch ? I made it so the number of recipients is shown when you select a mailing list, even before you click send.

I fetched cd7c202 which became 6db92f8 when rebased to master.

I'm talking about this:

```
+// This fires only when the "Envoyer" button is clicked
+document.getElementById('send-email-btn').addEventListener('click', async function (event) {
+    // Prevent the button to POST
+    event.preventDefault();
+    // Get the selected value in the dropdown
+    let mailing_list_token = document.getElementById('id_mailing_list').value;
+    // Result of the Ajax request is a dict {"count" : <int:number_of_recipients>}
+    let number_of_recipients = await get_number_of_recipients(mailing_list_token);
+    number_of_recipients = number_of_recipients["count"];
     ...
```
which, if I'm reading correctly, puts a click handler on the send button, and when that handler is called, it asks for the number of recipients.  If that number is positive, it presents a chicken box.  If it is zero, strangely, the user will be told, only now, that she has been wasting her time.

**Comment by JeffAbrahamson** [comment]
6db92f8 - listen**n**er is misspelled.

Here you do provide feedback on changing the dropdown menu, I think.  And you store it in the DOM.  So, on clicking the send button, why do you need to fetch it again instead of grabbing it from the DOM?  You'll save a few hundred milliseconds.

**Comment by JeffAbrahamson** [comment]
LGTM

**Comment by JeffAbrahamson** [comment]
```
+@StaffRequired
+def get_number_of_recipients(request, *args, **kwargs):
```
Why staff only?

**Comment by Shriukan33** [comment]
> ```
> +@StaffRequired
> +def get_number_of_recipients(request, *args, **kwargs):
> ```
> 
> Why staff only?

Changed for `tbe.may_send` permission check !

**Pull request merged**
