### PR TITLE
Fix jeff tb stuff

### PR DESCRIPTION
**Pull request by Shriukan33**
Minor fixes left on the previous PR #529

* Image not displaying properly on TB Launcher
* PEP8 format
* Cleanup by removing unused variables and prints
* Permissions are set

### CODE REVIEW

**Review by mcmikashi — APPROVED** [review]
LGTM

**Comment by mcmikashi** [comment]
Have little error on TopicBlogLauncher the str with no slug try to show the title but TopicBlogLauncher don't have title.
We can use headline maybe ?
```
def __str__(self):
    if self.slug:
        return f'{str(self.slug)} - ' + \
            f'ID : {str(self.id)}'
    else:
        return f'{str(self.headline)} - ID : {str(self.id)} (NO SLUG)'
```

**Comment by JeffAbrahamson** [comment]
> Have little error on TopicBlogLauncher the str with no slug try to show the title but TopicBlogLauncher don't have title. We can use headline maybe ?
> 
> ```
> def __str__(self):
>     if self.slug:
>         return f'{str(self.slug)} - ' + \
>             f'ID : {str(self.id)}'
>     else:
>         return f'{str(self.headline)} - ID : {str(self.id)} (NO SLUG)'
> ```

Good catch.  Yes, headline is a good option.

In this case, using `if-else` is surely the clearest option, but if the strings are shorter, it's worth knowing that you can say

    'something' if condition else 'other'

Example:

```
In [6]: q = ''

In [7]: 'something' if q else 'other'
Out[7]: 'other'

In [8]: q = 'dog'

In [9]: 'something' if q else 'other'
Out[9]: 'something'

In [10]:
```

**Comment by JeffAbrahamson** [comment]
This was merged yesterday.

**Comment by JeffAbrahamson** [comment]
8e7766c35 LGTM

**Comment by JeffAbrahamson** [comment]
35af0fda997 LGTM

**Comment by JeffAbrahamson** [comment]
00e63f9 LGTM

**Comment by JeffAbrahamson** [comment]
LGTM.

**Comment by JeffAbrahamson** [comment]
@Shriukan33 To you to merge and close.

**Pull request merged**
