### PR TITLE
Allow users to edit their MobilitoSession's location field

### PR DESCRIPTION
**Pull request by Shriukan33**
This view allows users to edit their mobilito sessions' string location field using an edit button.

The edit button is only visible to the user who created the mobilito session, or the persons with the permission to edit mobilito sessions.

Part of #1022

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
If I can't edit the text, then perhaps don't invite me to?
image

**Comment by JeffAbrahamson** [comment]
What does this message add to the simple fact that the message has, visibly, changed to whatever I just changed it to?
image

**Comment by Shriukan33** [comment]
I liked the positive feedback for the confirmation message :)

I admit I probably shouldn't have let the button be for older sessions, the only plus is can think of is that you can know why you can edit a session or not, as not not explained anywhere the 1 week rule

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JeffAbrahamson** [comment]
Aside from the messaging, it looks good.

I'm finding the user experience a bit jumpy.

Look at what happens on gh:
image
image

But for us we have lots of space (at least, in this particular case) and yet we reduce the width and crowd in some buttons and then it looks like
image
image

with, by the way, an errant and no longer correct message, because I've now started modifying the text and nothing has been saved yet
image

**Comment by JeffAbrahamson** [comment]
Hey, look, I hit cancel, and yet:
image

**Comment by JeffAbrahamson** [comment]
> I liked the positive feedback for the confirmation message :) I admit I probably shouldn't have let the button be for older sessions, the only plus is can think of is that you can know why you can edit a session or not, as not not explained anywhere the 1 week rule

Does anything still do this?  It feels very 1998 to me...

It's generally better to seek a good user experience than to make a clear experience that's wrong. ;-)  Inciting people to take actions that you have no intention of letting them complete is rarely, rarely the right thing to do...

**Comment by Shriukan33** [comment]
* Removed messaging
* Removed button if past a week
* Changed Modifier to Sauvgarder
* Text input now takes all available space

**Review by JeffAbrahamson — APPROVED** [review]
LGTM.

**Pull request merged**
