### PR TITLE
Add a link to press:new_item in press:list_items

### PR DESCRIPTION
**Pull request by mcmikashi**

### CODE REVIEW

**Comment by Shriukan33** [comment]
LGTM

**Comment by JeffAbrahamson** [comment]
LGTM

I can't help thinking that this could have been done for all TB* with something in the TB base template...

**Comment by Shriukan33** [comment]
> LGTM
> 
> I can't help thinking that this could have been done for all TB* with something in the TB base template...

Probably,  the link would have to be a variable then

**Comment by JeffAbrahamson** [comment]
> > LGTM
> > I can't help thinking that this could have been done for all TB* with something in the TB base template...
> 
> Probably, the link would have to be a variable then

We're developers, we can do variables.

**Pull request merged**
