### PR TITLE
Add OG data to mobilito_session_summary

### LINKED ISSUE #1042: Mobilito sessions need OG data
For the image, show (for now) the pie chart.

For the text, let's inspire by what vigilo does (don't remember off hand).

### PR DESCRIPTION
**Pull request by Shriukan33**
Closes #1042

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
I like the principle here, but does the text make any sense to someone who doesn't know the project?

What does this look like when shared to fb, tw, etc.?

**Comment by Shriukan33** [comment]
Also, I'm unsure about what text we should place in here. 
It's not explaining the Mobilito concept, but should it ? How should we proceed ? We got not that many chars to get our point across here.

**Comment by Shriukan33** [comment]
image

Fixed for twitter

**Comment by JeffAbrahamson** [comment]
> image
> 
> Fixed for twitter

Echos of pacman. 😆 
I should fix the labels...

**Comment by Shriukan33** [comment]
Haha it surely does echo, we should put the biggest value in yellow to get a pacman heheheh

How does that PR look to you ?

**Review by JeffAbrahamson — APPROVED** [review]
LGTM.  We'll improve it later.

**Pull request merged**
