### PR TITLE
Benja celery

### PR DESCRIPTION
**Pull request by Shriukan33**
Draft while tests aren't sorted, it breaks some because outbox is empty, now that mail are handed to Celery 

Based on #749 

This branch merge our celery settings and expand it to allow TopicBlogSendView to hand to celery the sending part.

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Why do you want a results backend?

**Comment by Shriukan33** [comment]
> Why do you want a results backend?

Simply allows you to see the task list status and history on django admin 

image

thought it would be a nice addition, although it's optional

**Comment by JeffAbrahamson** [comment]
In `celery.py` you've added comments that make sense in a tutorial, but seem a bit repetitive in production code.

**Comment by JeffAbrahamson** [comment]
You should generally never serialise objects to pass to celery.  You should have clear, well-defined interfaces that, mostly, are just a pk_id from some table and all the necessary information lives in that one table.

In addition, celery tasks need documentation, because the caller is not only not nearby, it is in another process that is not even guaranteed to be running on the same host or with the same code base, although in our setting both of those things are currently true.

**Comment by JeffAbrahamson** [comment]
Have you read the celery docs?  [In particular](https://docs.celeryq.dev/en/latest/getting-started/next-steps.html#calling-tasks),

> Also note that result backends aren’t used for monitoring tasks and workers: for that Celery uses dedicated event messages (see [Monitoring and Management Guide](https://docs.celeryq.dev/en/latest/userguide/monitoring.html#guide-monitoring)).

**Pull request closed without merging**
