### PR TITLE
press add search

### PR DESCRIPTION
**Pull request by mcmikashi**
- add search on press mention

### CODE REVIEW

**Review by Shriukan33 — CHANGES_REQUESTED** [review]
The search by date doesn't seem to work properly for me, my articles are dated from the 16/02 and 21/02, searching from 1/02 to 17/02 returns both articles. I tried with only the end date and it resulted the same. 

Did you got it to work on your side ?

**Comment by JeffAbrahamson** [comment]
You have a fair number of trailing spaces (`/ +$/`).

**Comment by mcmikashi** [comment]
- Clean the trailing space
- Fix the search logic

**Comment by JeffAbrahamson** [comment]
LGTM.

**Pull request merged**
