### PR TITLE
Benja 696 photo contest

### PR DESCRIPTION
**Pull request by Shriukan33**
This PR adds a form that allows logged-in users to submit an Image with various descriptions and context attached.

Photo are all saved in the same folder, although we can imagine a view that would display only the images from a given category, if needed. 
Although for now the django admin does the job quite well : 

image

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
I had to rebase to master, so this is my log:
```
42050a3|2022-04-25|Benjamin Mourgues| (HEAD, origin/benja-696-photo-contest) Add validation method to enforce image minimum resolution
6e714b3|2022-04-25|Benjamin Mourgues| Add UploadEntry and Confirmation views
e9bf3c0|2022-04-25|Benjamin Mourgues| Add photo app to INSTALLED_APPS settings
6d0e244|2022-04-25|Benjamin Mourgues| Add PhotoEntry model to admin panel
3c3e6f4|2022-04-25|Benjamin Mourgues| Create PhotoEntry model
77bb940|2022-04-25|Jeff Abrahamson| Pedagogical commit to bootstrap the Photo app
142b329|2022-04-20|Benjamin Mourgues| (origin/master, master) Change link and wording in Press unsub links
```

**Comment by JeffAbrahamson** [comment]
77bb940 - Could you please reword the commit message to explain what it really is?  Saying it is a pedagogical commit screams "not ready for merge".  (Aside: don't forget periods at end of sentences, except for first line.)

In addition, the "Hello" in views.py doesn't really belong.

I appreciate the vote of confidence in keeping so much of my sketch, but the idea was that you'd do something with it and squash that something into this commit. ;-)

**Comment by JeffAbrahamson** [comment]
3c3e6f - perhaps you meant to squash this with 77bb940?  It does seem to complete it somewhat.

Why is "quartier" capitalised and "pavés" not?

The documentation is a bit light.  Perhaps you could mention that this model assumes the Opération Piéton, the Hauts-Pavés/Saint-Félix photo competition that we are doing, and that it's intentionally not generalised to arbitrary competitions.  And that the intent is to maintain the flexibility to generalise it if needed for a second competition.

We can discuss this later, but I think we need to hold hands a whole lot more in the form comments.  This isn't TB, where the user is assumed to have some experience and some expertise.  I think we need gently to let users know that some fields are not required, that your telephone is perfectly acceptable as a camera, that your relationship could be that you live there, that the photo was taken there, that you work there, that you used to live or work there, that it reminds you of there, etc.

**Comment by JeffAbrahamson** [comment]
6d0e24447e doesn't do what the commit message says.  The model was already in admin, but you did add attributes.

**Comment by JeffAbrahamson** [comment]
e9bf3c06 - Shouldn't this be edited into 77bb940f + 3c3e6f?

**Comment by JeffAbrahamson** [comment]
6e714b3f - on the confirmation page, a CTA might be even clearer, wdyt?

The competition is called the "Opération Piéton", not the "concours photo du quartier des Hauts-Pavés Saint-Félix". ;-)

Aside: perhaps I'm just misreading the git log, but isn't photoentry_form.html just a rename and modification of upload_entry.html, not a new file and unrelated file deletion?

The confirmation view comment doesn't begin with a capital letter.  Am I misremembering, shouldn't comments end with periods?

**Comment by JeffAbrahamson** [comment]
42050a3 - the image validator is cool, I didn't realise we could do that.  We should add those for TB some day!

Here, we should be more forgiving.  If we ask for 1800 and the user sends us 1799, we certainly shouldn't refuse it.

I'd say fail below 1000x1000.

French question: isn't "La photo doit faire au moins 1800x1800 pixels" a bit moralising compared to something like "Résolution au moins 1800 x 1800 pixels"?

**Comment by JeffAbrahamson** [comment]
LGTM.

**Comment by Shriukan33** [comment]
Reworded !

**Pull request merged**
