### PR TITLE
iss325 - draft button

### PR DESCRIPTION
**Pull request by systemkwiat**
Not finished, just first version. Simple Draft.
Everything is sticked on jobs.html in asso_tn.
Using jquery the button copy the current url. Dont know why, but I had to add src attribute with jquery, because without it it didnt work

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Hey, cool, definitely appears to work!  ;-)

Yeah, I'm curious about the additional jquery include.  Is it the version (3.6.0 v 3.5.1)?  Or something else?

**Comment by JeffAbrahamson** [comment]
Could it be related to this?
```
Uncaught ReferenceError: $ is not defined
    <anonymous> http://localhost:8000/l/jobs?dog=cat&horse=cow:550
```

**Comment by JeffAbrahamson** [comment]
I wonder if this is because you are executing at page load time rather than at click time.  Not only is this inefficient, but at page load, you aren't coming before the other javascript loads.

Perhaps you should define a function at this spot and then add the function as the click handler?   I know you do define a function, so what I'm saying may be partially gibberish.

**Comment by Shriukan33** [comment]
Hey, I know it's been a while, I see you mentioned it's a draft, is there anything more you would like to add to this PR ? :slightly_smiling_face:

**Comment by Shriukan33** [comment]
It's been here for 6 months +, I'm closing for now but if you feel finishing it you're very welcome ;)

**Pull request closed without merging**
