### PR TITLE
Add social sharing button on mobilito session

### PR DESCRIPTION
**Pull request by Shriukan33**
Tracker blocking extensions like Ghostery and Disconnect will block the twitter button if enabled.

Part of #993

image

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Why do tracker-blocking extensions block the twitter button?
This is the one button that's really easy to do as a simple GET + fa icon...

**Review by JeffAbrahamson — CHANGES_REQUESTED** [review]
This is too local.  If we're going to add sharing, we should make everything shareable, not just mobilito pages.

We are adding a dependency on someone's github repo and on an unversioned bit of code.  Why is this a good idea?

If some bit of this causes privacy issues, then the whole thing should be unacceptable to us.

**Comment by Shriukan33** [comment]
> Why do tracker-blocking extensions block the twitter button? This is the one button that's really easy to do as a simple GET + fa icon...

Because the button that is loaded (the actual share on twitter button) is fetched on twitter's servers, apparently. 



> This is too local. If we're going to add sharing, we should make everything shareable, not just mobilito pages.

Can be quite easily done, we'd need to add to base template the scripts, and the div where appropriate. 



> We are adding a dependency on someone's github repo and on an unversioned bit of code. Why is this a good idea?
> 
> If some bit of this causes privacy issues, then the whole thing should be unacceptable to us.

I don't know what to tell you, you wanted to have social sharing buttons that didn't send data to third parties. That's what it does, as so far as I can see.

What's your requested change ? Getting rid of if or making it part of default template ?

**Comment by JeffAbrahamson** [comment]
> > We are adding a dependency on someone's github repo and on an unversioned bit of code. Why is this a good idea?
> > If some bit of this causes privacy issues, then the whole thing should be unacceptable to us.
> 
> I don't know what to tell you, you wanted to have social sharing buttons that didn't send data to third parties. That's what it does, as so far as I can see.
> 
> What's your requested change ? Getting rid of if or making it part of default template ?

You know about the npm incident, because of depending on 7 lines of code?

https://www.theregister.com/2016/03/23/npm_left_pad_chaos/

When you see that you're about to put something like this

    tps://panzi.github.io/SocialSharePrivacy/javascripts/jquery.socialshareprivacy.min.autoload.js

in your code, you should stop and think: what happens if this person pushes a bug or deletes his repo?  Is this dependence worth the risk?

Alternatives, depending on the size and complexity of the thing included, are forking the repo so that you upgrade on _your_ schedule, or just copying the code (what should have happened with that short npm snippet) or rewriting.

In this case, we're looking at ten year old code that's not particularly complex and that's no longer maintained.  We get very little benefit from maintaining a dependency.  It sounds like it's also simple enough that we can extract the little bit that we need and so be done with it.

**Comment by Shriukan33** [comment]
I'll go with a simpler implementation using FA icons and plain urls, as discussed in the issue :)

**Pull request closed without merging**
