### PR TITLE
Make arrows circular in photo gallery

### LINKED ISSUE #1045: photo gallery: circular arrows
The arrows should model a circular queue so that they don't disable at end of sequence.  We have no incentive to say "no" to our visitors.

### PR DESCRIPTION
**Pull request by Shriukan33**
First photo's previous is the last photo,
and the last photo's next is the first photo.

Closes #1045

### CODE REVIEW

**Review by JeffAbrahamson — APPROVED** [review]
LGTM, more or less.

Beginning developers tend to pull data from databases to manipulate it and then do something.  If those developers become more mature, they learn that they should do some of this work in the database.

I would really like you to learn sooner rather than later that doing things like `list(PhotoEntry.objects.filter(...))` is an anti-pattern.

**Comment by Shriukan33** [comment]
So I did find a query that would still hit the database once.
The performance seem to be a bit reduced (from ~115ms to load a photo:details page to 130ms) but at least it doesn't load into memory every photo ID like it did.

I also added Selenium tests to make sure we can actually click, fill the forms and vote on photo pages, as it involves some JS it seemed to be the best solution.

**Comment by Shriukan33** [comment]
Re-requesting review

**Review by JeffAbrahamson — APPROVED** [review]
LGTM.

**Pull request merged**
