### PR TITLE
Tbe create send record 532

### PR DESCRIPTION
**Pull request by Shriukan33**
Create send records on email sending, one for each recipient.

This PR also tweaks the model that had incoherent database requirements (like open time that can't be null), and adds the send record to admin.
The send records are searchable / order-able in Django admin.

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
When you comment out tests, maybe include a standard (i.e., always the same) disclaimer like `# Selenium / db re-entrancy bug, cf. #560`.

**Comment by JeffAbrahamson** [comment]
Is there a benefit to
```
unsubscribe_link = self.get_unsubscribe_link()
context["unsub_link"] = unsubscribe_link
```
over
```
context["unsub_link"] = self.get_unsubscribe_link()
```
?

**Comment by JeffAbrahamson** [comment]
This is worth testing behind the cloudflare proxy:
`get_current_site(self.request).domain`

**Comment by JeffAbrahamson** [comment]
fce8d564 - LGTM

**Comment by Shriukan33** [comment]
> Is there a benefit to
> 
> ```
> unsubscribe_link = self.get_unsubscribe_link()
> context["unsub_link"] = unsubscribe_link
> ```
> 
> over
> 
> ```
> context["unsub_link"] = self.get_unsubscribe_link()
> ```
> 
> ?
> 
> Similarly,
> 
> ```
> hostname = get_current_site(self.request).domain
> context["host"] = hostname
> ```

None, just me atomizing maybe a bit too much in the statements :sweat_smile: can use the one line version.

**Comment by Shriukan33** [comment]
@JeffAbrahamson Applied the requested changes

**Comment by Shriukan33** [comment]
Jobs not running, here are the tests : 
image

**Comment by JeffAbrahamson** [comment]
Only one quibble: I don't see how your comment on the final commit can be accurate, since the view is not modified in the commit.

**Comment by Shriukan33** [comment]
> Only one quibble: I don't see how your comment on the final commit can be accurate, since the view is not modified in the commit.

That's an older commit comment I forgot to edit :(

**Comment by Shriukan33** [comment]
@JeffAbrahamson Mind LGTM this PR ?

**Pull request merged**
