### PR TITLE
Save unsubscription time onclick on unsub link

### LINKED ISSUE #688: Update unsubscription time when clicked in email
When one clicks "Se désabonner" in emails, we should capture that and save it in the Send record.

### PR DESCRIPTION
**Pull request by Shriukan33**
The Unsubscription time is set as soon as you click "se désabonner"
in the email, even though you didn't confirm it afterwards.

Closes #688

I'm a bit dubious about why we would save it when on click instead of waiting for the POST on the form ?

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Am I confused or did you not test this?  ;-)

The `get()` will throw `self.model.DoesNotExist` if the object doesn't exist.

**Comment by JeffAbrahamson** [comment]
Also, given that you are compute `send_record`, perhaps it would be clearer to do that first, then use it twice, rather than using it twice.  (I admit I don't remember if django is clever enough not to do the query twice.)

**Comment by Shriukan33** [comment]
> Am I confused or did you not test this? ;-)
> 
> The `get()` will throw `self.model.DoesNotExist` if the object doesn't exist.

Did test, worked as described. 
The get didn't throw an error for me, did you send yourself a mail and clicked the unsub button ? How can I reproduce ?

**Comment by Shriukan33** [comment]
> Also, given that you are compute `send_record`, perhaps it would be clearer to do that first, then use it twice, rather than using it twice. (I admit I don't remember if django is clever enough not to do the query twice.)

https://docs.djangoproject.com/en/4.0/topics/db/queries/#caching-and-querysets-1
It's not 100% clear that it does cache the queryset in this case, so I'll go with the variable attribution and reuse :)

**Comment by JeffAbrahamson** [comment]
> > Am I confused or did you not test this? ;-)
> > The `get()` will throw `self.model.DoesNotExist` if the object doesn't exist.
> 
> Did test, worked as described. The get didn't throw an error for me, did you send yourself a mail and clicked the unsub button ? How can I reproduce ?

If I did that, the object would surely be present and I wouldn't trigger the error.  You can repro this in the shell.  Here, I don't expect object 3 to exist:

```
╭╴ (master $%=) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ python manage.py shell
Python 3.9.5 (default, Nov 18 2021, 16:00:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.3 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from topicblog.models import TopicBlogEmailSendRecord                                            

In [2]: TopicBlogEmailSendRecord.objects.get(pk=3)                                                       
---------------------------------------------------------------------------
DoesNotExist                              Traceback (most recent call last)
<ipython-input-2-9a69a55eef1d> in <module>
----> 1 TopicBlogEmailSendRecord.objects.get(pk=3)

~/src/jma/transport-nantes/tn_web/venv/lib/python3.9/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)
     83         def create_method(name, method):
     84             def manager_method(self, *args, **kwargs):
---> 85                 return getattr(self.get_queryset(), name)(*args, **kwargs)
     86             manager_method.__name__ = method.__name__
     87             manager_method.__doc__ = method.__doc__

~/src/jma/transport-nantes/tn_web/venv/lib/python3.9/site-packages/django/db/models/query.py in get(self, *args, **kwargs)
    433             return clone._result_cache[0]
    434         if not num:
--> 435             raise self.model.DoesNotExist(
    436                 "%s matching query does not exist." %
    437                 self.model._meta.object_name

DoesNotExist: TopicBlogEmailSendRecord matching query does not exist.

In [3]: 
```

**Comment by Shriukan33** [comment]
> > > Am I confused or did you not test this? ;-)
> > > The `get()` will throw `self.model.DoesNotExist` if the object doesn't exist.
> > 
> > 
> > Did test, worked as described. The get didn't throw an error for me, did you send yourself a mail and clicked the unsub button ? How can I reproduce ?
> 
> If I did that, the object would surely be present and I wouldn't trigger the error. You can repro this in the shell. Here, I don't expect object 3 to exist:
> 
> ```
> ╭╴ (master $%=) [virt]╶╮
> ╰ jeff@birdsong:transport_nantes $ python manage.py shell
> Python 3.9.5 (default, Nov 18 2021, 16:00:48) 
> Type 'copyright', 'credits' or 'license' for more information
> IPython 7.16.3 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: from topicblog.models import TopicBlogEmailSendRecord                                            
> 
> In [2]: TopicBlogEmailSendRecord.objects.get(pk=3)                                                       
> ---------------------------------------------------------------------------
> DoesNotExist                              Traceback (most recent call last)
> <ipython-input-2-9a69a55eef1d> in <module>
> ----> 1 TopicBlogEmailSendRecord.objects.get(pk=3)
> 
> ~/src/jma/transport-nantes/tn_web/venv/lib/python3.9/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)
>      83         def create_method(name, method):
>      84             def manager_method(self, *args, **kwargs):
> ---> 85                 return getattr(self.get_queryset(), name)(*args, **kwargs)
>      86             manager_method.__name__ = method.__name__
>      87             manager_method.__doc__ = method.__doc__
> 
> ~/src/jma/transport-nantes/tn_web/venv/lib/python3.9/site-packages/django/db/models/query.py in get(self, *args, **kwargs)
>     433             return clone._result_cache[0]
>     434         if not num:
> --> 435             raise self.model.DoesNotExist(
>     436                 "%s matching query does not exist." %
>     437                 self.model._meta.object_name
> 
> DoesNotExist: TopicBlogEmailSendRecord matching query does not exist.
> 
> In [3]: 
> ```

That's to be expected isn't it ? You can't edit a record that hasn't been created. 
I'd be worried if it didn't raise an error !

Why would you .get(id=3) in the console ? To test this is seems best to go through the use case : you've been sent a mail, you click on unsub

**Comment by JeffAbrahamson** [comment]
> That's to be expected isn't it ? You can't edit a record that hasn't been created. I'd be worried if it didn't raise an error !
> 
> Why would you .get(id=3) in the console ? To test this is seems best to go through the use case : you've been sent a mail, you click on unsub

You keep assuming that the world works according to plan.  That's not always the case.

Here's  URL:

https://www.example.com/go/look/at/this.

I have no idea why there's a period at the end.  Must be because the URL was copied and pasted by someone and put in a sentence and the person added a period.  And someone clicks it and lands on our site.  And you 500 instead of politely saying you don't recognise the payload.

Assume a kitten is brutally murdered every time your code serves a 500.

**Comment by Shriukan33** [comment]
> > That's to be expected isn't it ? You can't edit a record that hasn't been created. I'd be worried if it didn't raise an error !
> > Why would you .get(id=3) in the console ? To test this is seems best to go through the use case : you've been sent a mail, you click on unsub
> 
> You keep assuming that the world works according to plan. That's not always the case.
> 
> Here's a URL:
> 
> https://www.example.com/go/look/at/this.
> 
> I have no idea why there's a period at the end. Must be because the URL was copied and pasted by someone and put in a sentence and the person added a period. And someone clicks it and lands on our site. And you 500 instead of politely saying you don't recognise the payload.
> 
> Assume a kitten is brutally murdered every time your code serves a 500.

Now I understand what you meant, you wanted me to deal with the case an incorrect token is parsed !
Makes sense. 

I was thinking "Why is he surprised it doesn't work when clearly it shouldn't work ??", so display an alternative template basically.

**Comment by Shriukan33** [comment]
No kitten were harmed during this development process, PETA please don't sue 

_Just in case, I improved the error handling ..._

**Comment by JeffAbrahamson** [comment]
32d026a - if the `get` throws, you still don't catch it.  Either use filter and check for None, or use `try...except`, or present a cogent argument why you will _never_ 500 no matter what input the world provides.

**Comment by JeffAbrahamson** [comment]
2c01802d4 - why are you modifying `get_timed_token()`?

**Comment by Shriukan33** [comment]
> [32d026a](https://github.com/transport-nantes/tn_web/commit/32d026a391807c74e7dec8097476f3c88564fb1e) - if the `get` throws, you still don't catch it. Either use filter and check for None, or use `try...except`, or present a cogent argument why you will _never_ 500 no matter what input the world provides.

Opted for filter().first() and None check



> [2c01802](https://github.com/transport-nantes/tn_web/commit/2c01802d404b4b657e9ea6345994c151c7501517) - why are you modifying `get_timed_token()`?

I can't find the reason I had, deleted

**Comment by JeffAbrahamson** [comment]
Hey, sorry, but I have to keep hammering on user experience.  It's important, and whilst in any individual spot it seems (and is) minor, it adds up to constitute an overall experience.

---

Grandma receives an email and wants to unsubscribe.  She's a savvy senior: she is wary of clicking in emails, so she copies the link and pastes it into her browser.  Alas, she inadvertently types an extra key, and so we don't understand what it is.

Now think of how this would work in person.  You'd smile at the feisty activist in front of you and say "I'm sorry, I know you are valuable, but I didn't understand what you just said".

Instead, you've said "Nope, doesn't work".

---

Let it go this time, but we really need to focus on this, audit our code for every place we throw a 404, return a response not found, and make sure we are polite and smiling and optimistic, expressing the value the person on the other end of the connection represents.

**Comment by JeffAbrahamson** [comment]
There are, however, there are two serious bugs:

1.  You set the unsub time without looking.  If it's already been set, you've nothing to do on the send record, just make sure the user is unsubbed.  And say thanks, we love you, you're valuable, and you're off the list as requested.

2.  You do the save in `get_context_data()`.  But that is only called on GET.  You mustn't change server state on GET.  This belongs in the `post()` method (which, btw, should not normally call `get_context_data()`.

This, incidentally, is why unsub links generally present a button saying, roughly, "do you want to unsub user joe@example.com from list-of-lists?".  That lets you post.

**Comment by JeffAbrahamson** [comment]
cd827ac20 - on your strftime, it would be clearer to request "%F %T"

**Comment by Shriukan33** [comment]
Removed the server state change from get -> it was already done in POST anyway, this was coming from a misunderstanding. I thought you told me once that even if the user didn't confirm the unsubscription, clicking on the link would set an unsub time anyway (which is the Get) 

Also reworded the error messages

**Comment by JeffAbrahamson** [comment]
LGTM.

**Pull request merged**
