### PR TITLE
Add edit and add for Topicblog Press

### PR DESCRIPTION
**Pull request by mcmikashi**
For the template config tags i use:
```
  template_config_default = {
        "optional_fields_for_publication": (
                'header_image', 'header_description',
                'body_image', 'body_image_alt_text',
                'twitter_title', 'twitter_description',
                'twitter_image', 'og_title',
                'og_description', 'og_image'
        ),
        "one_of_fields_for_publication": [
                ['header_title', 'header_description'],
            ],
        # Dependent fields: if one in a group is provided, the others must
        # be as well before we can publish.
        "dependent_field_names": [
                ['body_image_1', 'body_image_1_alt_text'],
            ],
    }
    template_config = {
        'topicblog/content_press.html': {
            'user_template_name': 'Classic',
            'active': True,
            "fields": {
                'slug': True,
                'title': True,
                'subject': True,
                'body_text_1_md': True,
```
The template use (cta_1_slug ,cta_1_label, cta_2_slug and cta_2_label ) but  the TopicBlogPres object don't have cta. What should I do ?

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Please rebase to master and resolve conflicts.

**Comment by JeffAbrahamson** [comment]
> For the template config tags i use:
> 
> ```
>   template_config_default = {
>         "optional_fields_for_publication": (
>                 'header_image', 'header_description',
>                 'body_image', 'body_image_alt_text',
>                 'twitter_title', 'twitter_description',
>                 'twitter_image', 'og_title',
>                 'og_description', 'og_image'
>         ),
>         "one_of_fields_for_publication": [
>                 ['header_title', 'header_description'],
>             ],
>         # Dependent fields: if one in a group is provided, the others must
>         # be as well before we can publish.
>         "dependent_field_names": [
>                 ['body_image_1', 'body_image_1_alt_text'],
>             ],
>     }
>     template_config = {
>         'topicblog/content_press.html': {
>             'user_template_name': 'Classic',
>             'active': True,
>             "fields": {
>                 'slug': True,
>                 'title': True,
>                 'subject': True,
>                 'body_text_1_md': True,
> ```
> 
> The template use (cta_1_slug ,cta_1_label, cta_2_slug and cta_2_label ) but the TopicBlogPres object don't have cta. What should I do ?

Could it be that the template was copied from elsewhere without being modified?  And so then the template is faulty?

What is the git log on the template?  What does git blame or git annotate tell you?

**Comment by mcmikashi** [comment]
- rebase on master
- remove cta on the template
- move topicblog email edit on the good class

**Comment by JeffAbrahamson** [comment]
What is the difference between these two lines?  Will they ever exhibit different behaviour?
```
{% if page.body_image|length > 0 %}
{% if page.body_image %}
```

**Comment by JeffAbrahamson** [comment]
ddbf426 - please be more careful, proofread your commits.  You've again included extensive extraneous white space changes that distract in the diff.  If those changes merit making (e.g., PEP-8 compliance), please make them independently.

**Comment by JeffAbrahamson** [comment]
dbef53690 - could you please split this into two commits: one to move the TBEmail test, the other two add the TBPress test?

**Comment by mcmikashi** [comment]
- I rebase on master
- split the move and the add test commit
- {% if page.body_image|length > 0 %} is now {% if page.body_image %}
- Add a commit for PEP8 formatting

**Comment by mcmikashi** [comment]
- Fix the name and the url of topicblogPress edit test

**Pull request closed without merging**
