### PR TITLE
Improve the mailing list subcription

### PR DESCRIPTION
**Pull request by mcmikashi**
I use a get method to send the mail and the mailingslist to the last part but I dont know if this is the best way for do this. I think about session for do this too but I dont know what is the best.

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Feedback:
* careful about trailing white space
* your commit messages are a bit sparse: _how_ did you improve the list subscription?

**Comment by JeffAbrahamson** [comment]
Otherwise, LGTM.  @Shriukan33 ?

**Comment by Shriukan33** [comment]
Was about to do the same comment about .. well comments. You could expand a bit more on what you are doing, we know because it's recent, but this would be hard to get out of context. 
Otherwise LGTM, the get request doesn't seem to be an issue.

**Comment by JeffAbrahamson** [comment]
Hmm, the final stage is a GET with bare URL.  So a refresh re-submits the captcha, even though the user has successfully completed that stage.

I think after succeeding, the user should 302 to a URL that, even on refresh, is the same place and not a part of the subscribe process.

Eventually (soon!) we'll want to provide a custom page per list with fallback default.  But not today.

**Comment by JeffAbrahamson** [comment]
I'm merging because I'm still swimming in github docs explaining all the options and mechanisms for permitting people to merge, for auto-merge, etc.

It's not hard, and it doesn't reflect a volition to limit @mcmikashi , it's just that I'm time-constrained...

Like any good startup, we often start with things that don't scale...

**Pull request merged**
