### PR TITLE
Add 404 page template

### PR DESCRIPTION
**Pull request by Shriukan33**
This provides a friendlier experience for 404 errors

Error message is provided : 
image

Fallback
image

Part of #779

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
The language is much too technical.  The link?  Magic powers?

First, most users absolutely don't care what went wrong, they just want their furry kittens or whatever.  So the first thing you have to say, and you have to say it clearly and succinctly starting with an `<h2>`, is that something didn't work out.

Also, note that this is a 4xx error, not a 5xx, so clearly the problem _will_ persist.  This is careless language on our part.  We can certainly invite users to contact us, but it's disingenuous to suggest that trying the same link later will change the results.

Finally, there's not much point in a button to return to the home page, because we don't know here where the user was or where thy meant to go.  The full menus are above, and the error message should be followed by project squares or a teaser and project squares or something like that that just invites the user to browse more.  No user (aside from a few geeks) arrive at this page and want to think about it.  Either we incite them visually to continue on the site or we lose them.  You have less than a second to make your case.  The time simply to _decide_ what the home page might be like and weather or not I want to go there is enough to send most users back to youtube or tiktok or something.

**Comment by Shriukan33** [comment]
> The language is much too technical. The link? Magic powers?
> 
> First, most users absolutely don't care what went wrong, they just want their furry kittens or whatever. So the first thing you have to say, and you have to say it clearly and succinctly starting with an `<h2>`, is that something didn't work out. You get a couple words in the h2, and a tiny handful that stand alone as a first paragraph and that's it. If I can't read and understand it at a glance on my phone, you've lost me (statistically).
> 
> Also, note that this is a 4xx error, not a 5xx, so clearly the problem _will_ persist. This is careless language on our part. We can certainly invite users to contact us, but it's disingenuous to suggest that trying the same link later will change the results.
> 
> Finally, there's not much point in a button to return to the home page, because we don't know here where the user was or where thy meant to go. The full menus are above, and the error message should be followed by project squares or a teaser and project squares or something like that that just invites the user to browse more. No user (aside from a few geeks) arrive at this page and want to think about it. Either we incite them visually to continue on the site or we lose them. You have less than a second to make your case. The time simply to _decide_ what the home page might be like and weather or not I want to go there is enough to send most users back to youtube or tiktok or something.

Simplified the wording ! 

But I do disagree with the home page button, it's *really* common practice to do so : 
image
image
image
image
image
image
image
image
image
image
image
image


However, I do agree that the projects would fit nicely there ! 

I have pushed the normal version that is showing on the homepage, but I don't hate that the smaller version, see : 
image
Mobile : 
image


normal : 
image

The smaller one allow the desktop user to see without scrolling the titles. 

Wdyt ?

**Comment by JeffAbrahamson** [comment]
OK, I'm convinced that such buttons have a place.

I like your text.  Grammar question: on est à plein d'autres (choses ?) intéressantes ?

Should we strike the word "vraiment", it makes it sound like we're discouraging contact.

What does "normal" mean?  Do you mean desktop, which is the minority viewport on the web compared to mobile (over 50% market share)?  ;-)

**Comment by Shriukan33** [comment]
> I think this one looks best / is most readable: https://user-images.githubusercontent.com/70256364/171355444-6ce272a5-3447-4d16-aba7-8c14c9067272.png

This is the mobile version of the "narrow" version, with the blue section inside the message's div

**Comment by Shriukan33** [comment]
> I just deployed origin/master to beta.
> 
> image

We have a case of "But it works on my local machine !"
image

**Pull request merged**
