### PR TITLE
Add Django debug toolbar

### PR DESCRIPTION
**Pull request by Shriukan33**
This toolbar allows us to see the SQL queries that Django is running,
and the time it takes to run them.
It also shows us various data, like the context of the request.
See doc : http://django-debug-toolbar.readthedocs.org/en/latest/

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
LGTM

So you really need 0 in internal ip's?

**Comment by Shriukan33** [comment]
No I don't think it's mandatory

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JeffAbrahamson** [comment]
> No I don't think it's mandatory 

Also, it means something, and I don't think you mean to mean that.

**Comment by Shriukan33** [comment]
Removed it

**Pull request merged**
