### PR TITLE
Integration design gaelle

### PR DESCRIPTION
**Pull request by Shriukan33**
Integration of Gaelle's PR (#151) , with more precise commits.

Notable changes : 
* Social networks on the top navbar have been removed.

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
In 76fadc5 I don't understand.  The navbar doesn't stick to top of page (and I don't understand why that's desirable -- if I scroll down, shouldn't I be entitled to recover screen space?).

What in the commit changes something about the donation button?

**Comment by JeffAbrahamson** [comment]
In db2b97b, should the tax line perhaps be under the CTA rather than above?

**Comment by JeffAbrahamson** [comment]
In 4a46338 it drops to two columns instead of three rather two quickly to my taste.  On a 960 pixel window, I'm already down to two columns.

Why are the social media links in text rather than font-awesome icons?

**Comment by JeffAbrahamson** [comment]
In 96ccdf9, why are the social media links in text rather than font-awesome icons?

**Comment by JeffAbrahamson** [comment]
In f527d29, why do you change the formatting and remove the comments on the colours?

Also, you remove no-bullet-list, yet it's used in `mailing_list/forms.py`.

**Comment by JeffAbrahamson** [comment]
In 6b6f622, if these are better practices, could we add a comment that points to the practices we follow so that future maintainers can stick to it?

**Comment by JeffAbrahamson** [comment]
In f2c9b07 the diff suggests a copy/paste change of at least the commented blocks.

This is a diff that I'd expect to be almost entirely white space, but even `git diff -w` shows quite a lot of changes.

**Comment by JeffAbrahamson** [comment]
In 816fe1e, perhaps the name `background-ad-hoc-blue` should be renamed to `background-bleu-clair` or `background-mobiltains-bleu-clair` ?

```
╭╴ ((7605693...) $%) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ find . -type f -exec grep -H background-ad-hoc-blue \{\} \;
./topicblog/templates/topicblog/2020_bleu.html:<div class="row background-ad-hoc-blue"
./asso_tn/static/asso_tn/mobilitains.css:.background-ad-hoc-blue {
./asso_tn/templates/asso_tn/panel/qui_sommes_nous.html:<div class="row background-ad-hoc-blue" style="background-color:  #EAF3FC;">
╭╴ ((7605693...) $%) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ 
```

**Comment by JeffAbrahamson** [comment]
The change in c130013 seems wrong.  Shouldn't this replace these usages with the corresponding template tags?

**Comment by JeffAbrahamson** [comment]
7605693 - font-awesome?

**Comment by Shriukan33** [comment]
> In [76fadc5](https://github.com/transport-nantes/tn_web/commit/76fadc5aa34e70202fe794143310fc538c8fa278) I don't understand why this is desirable -- if I scroll down, shouldn't I be entitled to recover screen space? My first thought on the page as a user is that I want to find a way to disable it.
> 
> What in the commit changes something about the donation button?

The navbar disappears if you scroll down a bit, the idea was to make the donation button visible for more time.

**Comment by JeffAbrahamson** [comment]
> > In [76fadc5](https://github.com/transport-nantes/tn_web/commit/76fadc5aa34e70202fe794143310fc538c8fa278) I don't understand why this is desirable -- if I scroll down, shouldn't I be entitled to recover screen space? My first thought on the page as a user is that I want to find a way to disable it.
> > What in the commit changes something about the donation button?
> 
> The navbar disappears if you scroll down a bit, the idea was to make the donation button visible for more time.

Makes sense.  Some day when we have more traffic we should A/B test this.

**Comment by Shriukan33** [comment]
> In [76fadc5](https://github.com/transport-nantes/tn_web/commit/76fadc5aa34e70202fe794143310fc538c8fa278) I don't understand why this is desirable -- if I scroll down, shouldn't I be entitled to recover screen space? My first thought on the page as a user is that I want to find a way to disable it.
> 
> What in the commit changes something about the donation button?

Stickyness deleted 



> In [db2b97b](https://github.com/transport-nantes/tn_web/commit/db2b97b8ac32120ae4a7a61d2b92de59a5c3e32c), should the tax line perhaps be under the CTA rather than above?

Done ! 



> In [4a46338](https://github.com/transport-nantes/tn_web/commit/4a46338544c7e935dd8e1062f731e2486a890e68) it drops to two columns instead of three rather two quickly to my taste. On a 960 pixel window, I'm already down to two columns.

Made it stay on 3 column until small size (according to bootstrap, 576px) where it goes in column. 



> In [816fe1e](https://github.com/transport-nantes/tn_web/commit/816fe1e7fdd29f06ca98866eb67529503e8eb7cd), perhaps the name `background-ad-hoc-blue` should be renamed to `background-bleu-clair` or `background-mobiltains-bleu-clair` ?
> 
> ```
> ╭╴ ((7605693...) $%) [virt]╶╮
> ╰ jeff@birdsong:transport_nantes $ find . -type f -exec grep -H background-ad-hoc-blue \{\} \;
> ./topicblog/templates/topicblog/2020_bleu.html:<div class="row background-ad-hoc-blue"
> ./asso_tn/static/asso_tn/mobilitains.css:.background-ad-hoc-blue {
> ./asso_tn/templates/asso_tn/panel/qui_sommes_nous.html:<div class="row background-ad-hoc-blue" style="background-color:  #EAF3FC;">
> ╭╴ ((7605693...) $%) [virt]╶╮
> ╰ jeff@birdsong:transport_nantes $ 
> ```

Did change the occurrences of ad-hoc-blue class. Now this is backgrond-mobilitains-bleu-clair,; as you suggested.

Any comment I didn't mention is not handled yet, but about the font-awesome topic, they were not in the original PR, so didn't add them yet.
However this is in my next tasks, this is all a work in progress. 
I'll push the changes I mentioned so you can suggest other modifications if you want, but there is more to come.

**Comment by Shriukan33** [comment]
Alright, did apply all your suggestions except for this one --> 

> The change in [c130013](https://github.com/transport-nantes/tn_web/commit/c1300138c64d86f4cce2d89fe9e18cd3b6a7398e) seems wrong. Shouldn't this replace these usages with the corresponding template tags?

I'm going to examine what you want here.

**Comment by JeffAbrahamson** [comment]
Maybe fix the description of ddd6b90 now that sticky isn't present?

**Comment by JeffAbrahamson** [comment]
6d5a68d - careful about EOL white space, but don't worry about it this time for 2 x 2 spaces.

6d5a68d - why add [ionicons](https://ionicframework.com/docs/v3/ionicons/) instead of using [fontawesome](https://fontawesome.com/v4.7/icon/instagram), already included?

052d90d - why do you remove the comments and formatting on the colours?

fcc8540 - please put the url in the doc so that future developers/maintainers will actually see it.  Also, vertical space is really precious, adding more means seeing less code.  I'm not keen on adding gratuitous blank lines between every block except where it really improves readability.

5d3892c - looks like it should be two commits.  In addition, the minor change on base is an enormous diff.

3b13a20 - reminder, white space, please diff before committing.  Also, use `{% don_bouton %}` instead of `{% url_don %}` in a button.  It's DRYer.

**Comment by Shriukan33** [comment]
> [6d5a68d](https://github.com/transport-nantes/tn_web/commit/6d5a68dc45a012d631ca8d8a85ce641e65cadf01) - careful about EOL white space, but don't worry about it this time for 2 x 2 spaces.

Added final blank line

> [6d5a68d](https://github.com/transport-nantes/tn_web/commit/6d5a68dc45a012d631ca8d8a85ce641e65cadf01) - why add [ionicons](https://ionicframework.com/docs/v3/ionicons/) instead of using [fontawesome](https://fontawesome.com/v4.7/icon/instagram), already included?

Fixed, didn't realize that font-awesome also do that

> [052d90d](https://github.com/transport-nantes/tn_web/commit/052d90ddca9779db82acb0246948cb17541e480f) - why do you remove the comments and formatting on the colours?

My bad, didn't see that change. Back to original comments and format.

> [fcc8540](https://github.com/transport-nantes/tn_web/commit/fcc85408efaa8ebf19a3c745e01e70792c4f5c43) - please put the url in the doc so that future developers/maintainers will actually see it. Also, vertical space is really precious, adding more means seeing less code. I'm not keen on adding gratuitous blank lines between every block except where it really improves readability.

Removed the blank lines between rulesets.
Also added the url to CSS guidelines from mozzila's website. 

> [5d3892c](https://github.com/transport-nantes/tn_web/commit/5d3892cb99f524ce38c0714a46a286e1332436b0) - looks like it should be two commits. In addition, the minor change on base is an enormous diff.

Broke it down to smaller commit.The base also had formatting going on, hence the big diff.

> [3b13a20](https://github.com/transport-nantes/tn_web/commit/3b13a2045b965e64cfd6c46558c5c59405b4341a) - reminder, white space, please diff before committing. Also, use `{% don_bouton %}` instead of `{% url_don %}` in a button. It's DRYer.

Done. Modified don.py to have something closer to what's forecast on the charte graphique, to be fine tuned soon. Didn't implement yet because this PR is mainly about integrating Gaelle's changes (tweaked a bit for favicon and banner, sorry)

**Comment by JeffAbrahamson** [comment]
a93a026 - could you just add to the comment that the commit contains no changes other than white space (assuming that's true, but it looks to be)?

006d183 - It should be "these", not "those".  Hic, haec, hoc, and all that.

7b6194c - out of curiosity, why "btn-primary" ?

Otherwise, LGTM, ok to 
* make above mods
* deploy to beta and confirm still what you expect
* merge to master
* deploy to prod
* again, test that it's what you expect

Thanks!

**Comment by Shriukan33** [comment]
> [a93a026](https://github.com/transport-nantes/tn_web/commit/a93a02655d622fed3e3be0b756a8ce2cd27723ef) - could you just add to the comment that the commit contains no changes other than white space (assuming that's true, but it looks to be)?

Added

> [006d183](https://github.com/transport-nantes/tn_web/commit/006d1834a60d8fa1d860ff3c1dbaa803d0ffd644) - It should be "these", not "those". Hic, haec, hoc, and all that.

Never studied latin :) Reworded ! 

> [7b6194c](https://github.com/transport-nantes/tn_web/commit/7b6194c3baf220c7f491dbf755258a5478cadc49) - out of curiosity, why "btn-primary" ?

it was the closest to my goal, but I did make a new style to be more precise in the look. 

> Otherwise, LGTM, ok to
> 
>     * make above mods
> 
>     * deploy to beta and confirm still what you expect
> 
>     * merge to master
> 
>     * deploy to prod
> 
>     * again, test that it's what you expect
> 
> 
> Thanks!

Added some commits which I believe can fit this PR, those are modifications suggested by Gaelle. 
Font change to MontSerrat, CTA button change, and Navigation button and their behaviors.

**Pull request merged**
