### PR TITLE
Drop the end of year banner

### PR DESCRIPTION
**Pull request by JeffAbrahamson**
We added a button at the end of 2021 to encourage donations.  (We
received none.)  It's not something we intended to keep long term.
Let's drop it now that the new year has started.

### CODE REVIEW

**Comment by Shriukan33** [comment]
Maybe you want to turn off the banner then setting banner_is_present to false is enough. 
If you want to get rid of the whole banner feature, then you also need to delete it in the base_mobilitains.html template  :slightly_smiling_face:

**Comment by Shriukan33** [comment]
> Agreed, but we would be unlikely to re-enable the same banner in the future, so it would just be dead code executing on each request for no reason.

Ok, then I'd rather have the base template updated as well, so it doesn't try to render something that doesn't exist anyway

**Comment by JeffAbrahamson** [comment]
It's in a `{% if ... %}` block.  I thought the point of the mechanism was to enable us to activate it and deactivate it from time to time.  Did I misunderstand?

**Comment by Shriukan33** [comment]
Nah you're right. But as you delete the code that enables it, I wonder why keeping it then ? Else we could make banner_is_present = False and put the rest under a if condition (if banner_is_present: ... ) 

This way only the bool is evaluated, which is not that expensive. 

The only thing that bugs me is why keeping the HTML in the template if the code responsible to make it appear is deleted. Enabling it again would mean writing again the very same code. 
So in my head it's either we delete both, or we put that under a condition so we can enable it later if we feel like it ? 

Is there something I'm not seeing ?

**Comment by JeffAbrahamson** [comment]
Yeah, next time we'd write code like
```
context["banner_is_present"] = True
context["banner_text"] = "New stuff"
# etc.
```
But what we wouldn't have to do is think about how the mechanism works or how to format it.

**Comment by Shriukan33** [comment]
> Yeah, next time we'd write code like
> 
> ```
> context["banner_is_present"] = True
> context["banner_text"] = "New stuff"
> # etc.
> ```
> 
> But what we wouldn't have to do is think about how the mechanism works or how to format it.

Ok, so you'd rather delete the code than making it conditional ? 
Either way, it's easy enough to get back to this, even in 6 months. Adding a var to context shouldn't be too hard haha

LGTM

**Pull request merged**
