### PR TITLE
Add notes section to TB objects

### LINKED ISSUE #437: Add notes section to TBObject
Let's add a text field to TBObject and a field to the edit forms so that author's can add their notes, such as research links and URL's, directly to the articles they write.

These are things we won't display, but it lets us track and hold on to them more easily.

### PR DESCRIPTION
**Pull request by Shriukan33**
These fields wont be displayed, they are only there
for references for the editors.

Can consult them in the edit form or through django admin for now. 

Closes #437

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Why does the commit have _two_ migrations?  Can you clean that up?

**Comment by JeffAbrahamson** [comment]
"notes section" describes something visual, not a field.  A field name like "author_notes" would make much more sense.

On the form, perhaps we could provide feedback that it is internal and won't display to users?

**Comment by JeffAbrahamson** [comment]
The social media section of the edit form is already really long.  Perhaps we should put this on the admin page instead, or even better, create a new section for it?

**Comment by Shriukan33** [comment]
Added a new tab, holding the new field
Made it one migration
Renamed it author notes
Added a precision in the form informing the user that these notes aren't displayed on the website.

**Comment by JeffAbrahamson** [comment]
LGTM

**Pull request merged**
