### PR TITLE
Ajax button benjamin

### PR DESCRIPTION
**Pull request by Shriukan33**
Created just a basic webpage with a placeholder text. 
It adds /buttons as a valid URL. 

Will implement the button counter on this page.

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Comments:
* In 7bdb6c1 you surely shouldn't commit Pipfile and Pipfile.lock
* It's ok just to print the timestamp but not store it in the dict.  This will simplify the dict.

**Comment by Shriukan33** [comment]
Will add those two in my gitignore!

Noted for the dict, had something like {"A" :  {"clicks" : 0, "timestamps" : [] } } but didn't figure out yet how to update it.
I'll add it to the print statement "Seen {letter} at {timestamp}".

**Comment by JeffAbrahamson** [comment]
Adding to .gitignore is a good idea.

If you want to practice your git fu, you can even edit the old commit and so remove them from history.  (This is your branch, after all, you're allowed to modify history.)

**Comment by JeffAbrahamson** [comment]
If you were going to track timestamps, I'd be inclined to hold something more like

```
{"A": [t1, t2, t3, ...], "B": [...], ...}
```
Then the count is just `len(d["A"])`, which is a constant time procedure.

**Comment by Shriukan33** [comment]
There are still some artifacts of tries in the ids of html document / Js script, but the app does return on the server the print on click and updates a dict with total number of clicks on each button, as asked in the requirements

Todo: 
Update the value on client side

**Comment by Shriukan33** [comment]
The app does display 4 buttons namely A,B,C and D along with 4 counters. 
Each click on a button prints server side timestamp and the letter of the button, and updates a dictionnary with total number of clics on each. 
Upon refresh, the counter resets without needing a server restart. 

I believe there is a more elegant way to do it especially on the script.

**Comment by JeffAbrahamson** [comment]
Cool.  Some initial feedback just on the commit stream:
* .vscode/settings.json is about you and shouldn't be present
* commit 489603 does quite a lot more than just removing pipfiles

**Comment by JeffAbrahamson** [comment]
```
╭╴ ((d140832...) %) [virt]╶╮
╰ jeff@starshine:transport_nantes $ ROOT_URLCONF=transport_nantes.urls_m DEFAULT_SITE_ID=1       python manage.py runserver --settings=transport_nantes.settings_tn
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 58, in _load_all_namespaces
    namespaces = [
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 59, in <listcomp>
    ':'.join(parents + (url.namespace,)) for url in url_patterns
TypeError: sequence item 0: expected str instance, dict found
^C╭╴ ((d140832...) %) [virt]╶╮
╰ jeff@starshine:transport_nantes $ 
```

**Comment by Shriukan33** [comment]
> 
> 
> Using the sample invocation in NOTES:
> 
> ```
> ╭╴ ((d140832...) %) [virt]╶╮
> ╰ jeff@starshine:transport_nantes $ ROOT_URLCONF=transport_nantes.urls_m DEFAULT_SITE_ID=1       python manage.py runserver --settings=transport_nantes.settings_tn
> Watching for file changes with StatReloader
> Performing system checks...
> 
> Exception in thread django-main-thread:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
>     fn(*args, **kwargs)
>   File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
>     self.check(display_num_errors=True)
>   File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
>     all_issues = self._run_checks(
>   File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
>     return checks.run_checks(**kwargs)
>   File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
>     new_errors = check(app_configs=app_configs)
>   File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
>     all_namespaces = _load_all_namespaces(resolver)
>   File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 58, in _load_all_namespaces
>     namespaces = [
>   File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 59, in <listcomp>
>     ':'.join(parents + (url.namespace,)) for url in url_patterns
> TypeError: sequence item 0: expected str instance, dict found
> ^C╭╴ ((d140832...) %) [virt]╶╮
> ╰ jeff@starshine:transport_nantes $ 
> ```

Curious, I'm not using this line, I simply py manage.py runserver. 
Investigating what's wrong with this command.

**Comment by JeffAbrahamson** [comment]
Yes, it kinda works without the first part of the command.  That complexity was introduced with the sites framework and the split urls_tn and urls_m.  Which I should clean up.

There are many things I should do...

It appears that you did not commit the template buttons.html.

**Comment by Shriukan33** [comment]
> Yes, it kinda works without the first part of the command. That complexity was introduced with the sites framework and the split urls_tn and urls_m. Which I should clean up.
> 
> There are many things I should do...
> 
> It appears that you did not commit the template buttons.html.

I think I committed it in the d140832, did I messed with the pull request?
It's my first fork so I might not get everything right yet.

**Comment by JeffAbrahamson** [comment]
Indeed, you did, [here](https://github.com/Shriukan33/tn_web/blob/ajax_button_Benjamin/transport_nantes/buttons/views.py#L40).  

It would be better form to put it in `buttons/templates/buttons/buttons.html` so that you don't collide with other modules.  But beyond that, I'm not sure.  Could it be that you didn't add the new app to `settings.py`?

**Comment by Shriukan33** [comment]
> 
> 
> Indeed, you did, [here](https://github.com/Shriukan33/tn_web/blob/ajax_button_Benjamin/transport_nantes/buttons/views.py#L40).
> 
> It would be better form to put it in `buttons/templates/buttons/buttons.html` so that you don't collide with other modules. But beyond that, I'm not sure. Could it be that you didn't add the new app to `settings.py`?

I see it now. I did add the new app in the settings_local.py, which is untracked by Git, as it's in the .gitignore. 
transport_nantes\transport_nantes\settings_local.py
I added it along with the others in the settings.py file. 

Also, noted for the buttons/buttons.html file, modified accordingly. Running tests on my side to see if everything works fine and commit.

**Comment by JeffAbrahamson** [comment]
Awesome!  (I'll have to test it later, I'm at work now...)

So as a last sub-task, if this were a branch that we really planned to merge, we'd want to clean it up.  Do you think you can figure out how to rebase it into something coherent where files that shouldn't have been committed never were (in the sense of no longer in commits that will be merged), and with commit messages that apply to each commit?

[This article](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) is a classic summary of what a good commit message looks like.  [This](https://www.freecodecamp.org/news/a-beginners-guide-to-git-how-to-write-a-good-commit-message/) is a rather longer article on the subject.

Once you do that, you'll have to `git push --force` (or call it a different branch, but that would be mess up the PR).  If you don't understand why you'll need to force, we can talk about it later.  It's worth understanding.  Remember that the reflog is there to help you recover from disasters.

**Comment by Shriukan33** [comment]
On it ! Got to admit that Pipfile and .vscode give me some hard times, I need to figure how to remove them from my commits using rebase. Time to get 5th Dan in git-fu !

**Comment by JeffAbrahamson** [comment]
There are a couple ways to do it and plenty of suggestions on SO.
Ping if you get too confused on it.

**Comment by Shriukan33** [comment]
I think I've got it ? Let me know if this is what you expected.

**Comment by JeffAbrahamson** [comment]
1.  Excellent, well done.
2. Have you tried running it as two users at once?  ;-)

**Comment by Shriukan33** [comment]
> 1.  Excellent, well done.
> 2. Have you tried running it as two users at once?  ;-)
> 
> BTW, I think there's a one-word fix, but I'm not 100% sure.  Do you see it?

Thank you!

I'm on mobile, but according to your question I suppose that if another user presses a button while another resets it's page, the counter is reset to 0 for the other user as well.
I don' t know the immediate fix, I guess it has to do with the js query? I'll need to check that on my pc

**Pull request closed without merging**
