### PR TITLE
Add a Crowdfunding page

### PR DESCRIPTION
**Pull request by Shriukan33**
This page aims to inform the visitors that a Crowdfunding campaign is
taking place.

Part of #294

TODO : 
The bottom-button class needs some adjustements 
The text is still lorem ipsum
The image is a placeholder
The 200€ image has a crooked mobilitains.fr text 
Responsive hasn't been tested yet.

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
You clearly need to override something in the styles block, but duplicating the whole block is assuredly not the best way to do this.  Perhaps add to `base_mobilitain.html` something like
```
   {% block styles %}
+ {% block localstyles %}{% endblock localstyles %}
```

`crowdfunding.html` has really long lines.

Careful about trailing white space.

Why do you change `topicblog/templates/topicblog/content.html`?  Looks like white space only and accidental.

I'd vote for putting the CF images in a subdir, e.g., in `.../static/asso_tn/2021-cf/`.  It's easy today and in its tidyness could make life easier in the future.  Wdyt?

**Comment by JeffAbrahamson** [comment]
Let's make the URL contain the year so that next year's crowdfunding isn't _obliged_ to think about this year's.

Maybe `crowdfunding-2021`?

**Comment by JeffAbrahamson** [comment]
ce n'est pas _une_ campagne?

**Comment by Shriukan33** [comment]
> ce n'est pas _une_ campagne?

Si, et _un_ financement participatif, je ne sais pas à quel passage tu fais référence ? Sûrement une typo

**Comment by Shriukan33** [comment]
> You clearly need to override something in the styles block, but duplicating the whole block is assuredly not the best way to do this. Perhaps add to `base_mobilitain.html` something like
> 
> ```
>    {% block styles %}
> + {% block localstyles %}{% endblock localstyles %}
> ```

We don't intend to reuse that template, so I cherry picked whatever I needed to make it work.  Is it necessary to get back on this ? 


> `crowdfunding.html` has really long lines.
> 
> Careful about trailing white space.

Oops, my IDE doesn't warn me about trailing whitespaces on html documents, I tend to forget them ! Sorry

> Why do you change `topicblog/templates/topicblog/content.html`? Looks like white space only and accidental.

What are you referring to ? 

> I'd vote for putting the CF images in a subdir, e.g., in `.../static/asso_tn/2021-cf/`. It's easy today and in its tidyness could make life easier in the future. Wdyt?

Good point, will do that. asso_tn/static/asso_tn has been a mess, now it would be a bit harder to not break images but never too late to take good habits !

**Comment by JeffAbrahamson** [comment]
> > ce n'est pas _une_ campagne?
> 
> Si, et _un_ financement participatif, je ne sais pas à quel passage tu fais référence ? Sûrement une typo

L 113

**Comment by JeffAbrahamson** [comment]
> We don't intend to reuse that template, so I cherry picked whatever I needed to make it work. Is it necessary to get back on this ?

It's 2 minutes today.
The temporary has a habit of living a very long time.

**Comment by JeffAbrahamson** [comment]
> What are you referring to ?

How's your git-fu doing?  ;-)

image

**Comment by Shriukan33** [comment]
> > > ce n'est pas _une_ campagne?
> > 
> > 
> > Si, et _un_ financement participatif, je ne sais pas à quel passage tu fais référence ? Sûrement une typo
> 
> L 113
> 
> Do you know how to ask your editor to show you all instances of a word or phrase? image

Yes, my brain somehow skipped it, like in the
the double the example I guess haha, this is fixed.



> > We don't intend to reuse that template, so I cherry picked whatever I needed to make it work. Is it necessary to get back on this ?
> 
> It's 2 minutes today. The temporary has a habit of living a very long time.

Done



> > What are you referring to ?
> 
> How's your git-fu doing? ;-)
> 
> image

This was not a whitespace, there was an extra double quote that actually messed up the tag.

**Comment by JeffAbrahamson** [comment]
> This was not a whitespace, there was an extra double quote that actually messed up the tag.

Aha, indeed.  Well done.

Perhaps this should be a separate commit, then, so that the change is understandable and this commit is (epsilon) simpler?

**Comment by JeffAbrahamson** [comment]
LGTM.

**Comment by Shriukan33** [comment]
> LGTM, modulo the one TB change.

Splitted into two commits, as requested ! 
Images are still to be updated as well, but overall this is how it will look.

**Comment by JeffAbrahamson** [comment]
LGTM

**Pull request merged**
