### PR TITLE
Add Selenium test to stripe app

### PR DESCRIPTION
**Pull request by Shriukan33**
Current coverage of stripe_app's views.py is now at 88%, last lines missing are mostly
error catch and their log lines, so few holes but still good enough
to be reassured that a normal flow runs smoothly for now.

Part of #197

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Does `make test` still run all local tests?

**Comment by JeffAbrahamson** [comment]
LGTM.

The tests take forever to run.  Is this normal?  It's been over a minute whilst it runs `chromedriver`.

**Comment by JeffAbrahamson** [comment]
I'm unable to run tests successfully.  After a _very_ long wait running `chromedriver`, I see this (many times, this is but one instance):

```
====== WebDriver manager ======
Could not get version for google-chrome with the any command: google-chrome --version || google-chrome-stable --version
Current google-chrome version is UNKNOWN
Get LATEST chromedriver version for UNKNOWN google-chrome
Driver [/home/jeff/.wdm/drivers/chromedriver/linux64/98.0.4758.102/chromedriver] found in cache
E.........
======================================================================
ERROR: test_one_time_payment_flow (stripe_app.tests.TestStripeAppSelenium)
Test that we can do a one time payment with a preset amount
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jeff/src/jma/transport-nantes/tn_web/transport_nantes/stripe_app/tests.py", line 200, in setUp
    self.browser = WebDriver(ChromeDriverManager().install(),
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/jeff/src/jma/transport-nantes/tn_web/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x565197896b33 <unknown>
#1 0x56519735f6d8 <unknown>
#2 0x565197385462 <unknown>
#3 0x5651973819e9 <unknown>
#4 0x56519737dfca <unknown>
#5 0x5651973b8e0a <unknown>
#6 0x5651973b2f53 <unknown>
#7 0x565197388a0a <unknown>
#8 0x565197389ad5 <unknown>
#9 0x5651978c82fd <unknown>
#10 0x5651978e14bb <unknown>
#11 0x5651978ca0d5 <unknown>
#12 0x5651978e2145 <unknown>
#13 0x5651978bdaaf <unknown>
#14 0x5651978feba8 <unknown>
#15 0x5651978fed28 <unknown>
#16 0x56519791948d <unknown>
#17 0x7f6fea757450 <unknown>
```

**Comment by JeffAbrahamson** [comment]
I'm running tests with `make test`.

**Comment by JeffAbrahamson** [comment]
wtf?
```
----------------------------------------------------------------------
Ran 74 tests in 376.817s

FAILED (errors=6)
Destroying test database for alias 'default'...
make: *** [Makefile:2: test] Error 1

real	6m21.004s
user	0m26.965s
sys	0m17.900s
╭╴ ((a2593a7...) $%) [virt]╶╮
╰ 2,[T] jeff@birdsong:transport_nantes $
```

**Comment by Shriukan33** [comment]
With the VM update (chrome branch), this should be mergeable ?

**Comment by JeffAbrahamson** [comment]
If tests pass in vagrant, LGTM.

**Comment by Shriukan33** [comment]
image
Confirmed !

**Pull request merged**
