### PR TITLE
Add test for TopicBlogLauncher

### PR DESCRIPTION
**Pull request by mcmikashi**
Last part of 530.
Need some fix

### CODE REVIEW

**Comment by mcmikashi** [comment]
Got some weird error on TB Launcher when testing the page that use topicblog:view_launcher_by_pkid_only as name with the staff user:
 ```
   url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "M:\studi\mobilitains\tnbonenv\lib\site-packages\django\urls\base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "M:\studi\mobilitains\tnbonenv\lib\site-packages\django\urls\resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'view_item_by_slug' with arguments '('',)' not found. 1 pattern(s) tried:
['tb/t/(?P<the_slug>[-a-zA-Z0-9_]+)/\\Z']
```

**Review by Shriukan33 — CHANGES_REQUESTED** [review]
Figured out the origin of this bug : 
Notice the test mentions "view_item_by_slug", while you are testing "view_launcher_by_pkid_only"
Why would this happen only on staff ? What different when you are staff ? An anonymous visitor is redirected to login, and if you don't have the permission you 403.The staff user has the appropriate permission so it actually renders the template ! 

If you scan the template, you can see this :
https://github.com/transport-nantes/tn_web/blob/0e154fa9ac5ccdbbce8b75a8d730cf19ef1982dd/transport_nantes/topicblog/templates/topicblog/content_launcher.html#L56

In this test, you're testing what happens if we try to access a TBLA item that has no slug : 
https://github.com/transport-nantes/tn_web/blob/0e154fa9ac5ccdbbce8b75a8d730cf19ef1982dd/transport_nantes/topicblog/tests_topic_blog_epl.py#L890

So once it gets to the rendering part, it has no argument to give in the template resulting in the error you describe. 

I wrote this to fix it : 
```
        {% if page.slug %}
            <a href="{% url 'topic_blog:view_item_by_slug' page.slug %}">
        {% else %}
            <a href="#">
        {% endif %}	    
            <div class="shadow-md">
                <img class="rounded"
                {% if page.launcher_image %}
                    src="{{ page.launcher_image.url }}"
                    alt="{{ page.launcher_image_alt_text }}"
                {% else %}
                    {% comment %}Puts a grey placeholder image 667x667 px{% endcomment %}
                    src="https://via.placeholder.com/667"
                {% endif %}
                
                style="width:100%">
            </div>
            <div class="caption pt-2">
                <h3 class="font-weight-light"
                style="font-variant: all-small-caps;
                    font-size: 150%;">{{ page.headline }}</h3>
                <p>
                {% tn_markdown page.launcher_text_md %}
                </p>
            </div>
```

Notice that another error would occur because the launcher is slug less but also image-less, so calling `page.launcher_image.url` would also have failed.

**Review by Shriukan33 — COMMENTED** [review]
I think we can use tb_edit_template.html ?

**Comment by mcmikashi** [comment]
Yes I use this file on my next PR.

**Comment by JeffAbrahamson** [comment]
9087bf7 adds a template but doesn't use it, what is this for?  The commit comment gives no clue.

**Comment by JeffAbrahamson** [comment]
eb80ba846 commit comment doesn't explain what was wrong, only that you are fixing it.  Could you give a proper explanation of the problem and the solution?

If there is no slug, then your link will go nowhere.  Why do you render it at all?  Also, this should never happen for unprivileged users, only for editors whilst making a new launcher but not done yet.  That is, why would we want a launcher with no slug?  (I'm assuming `page.slug` is being set somewhere to `article_slug`.)

Is this not a reasonable constraint for the "ready to publish" function?

**Comment by JeffAbrahamson** [comment]
2a5b37ce7 - given that you're on your own branch, might this not have been squashed into `2a5b37ce7^`?

**Comment by mcmikashi** [comment]
> If there is no slug, then your link will go nowhere. Why do you render it at all? Also, this should never happen for unprivileged users, only for editors whilst making a new launcher but not done yet. That is, why would we want a launcher with no slug? (I'm assuming `page.slug` is being set somewhere to `article_slug`.)

Yes this error only happen on staff user no auth will be redirected to auth and normal user get a 403.

**Comment by mcmikashi** [comment]
- I update the message of all commit 
- I delete the link when the object doesn't have a slug
- I sqash the fix comment commit into the last commit

**Comment by JeffAbrahamson** [comment]
Come on, six months from now no one will understand your comment in 59aac0e3.  What test fails?  Why does it fail?  How does adding this template change anything?

**Comment by JeffAbrahamson** [comment]
a06502e309a - Do you want to add a comment to the template that explains that this view only happens during launcher development and that the slug is really `article_slug` here and that it is required for publication?

**Comment by mcmikashi** [comment]
- Update the commit message of first and second commit.
- add comment on the template content_launcher.html

**Comment by JeffAbrahamson** [comment]
This appears to be a single commit based on code that is under review elsewhere, so I'll hold off on review until the other code is merged and this rebases.

What does "epl" mean?

**Comment by mcmikashi** [comment]
> What does "epl" mean?

epl mean Email Press Launcher

**Comment by JeffAbrahamson** [comment]
> > What does "epl" mean?
> 
> epl mean Email Press Launcher

How will anyone ever know that?

**Comment by mcmikashi** [comment]
- I update the first and second commit message
- I rename the file tests_topic_blog_epl.py  to tests_topic_blog_part_2.py
Maybe I can split the file into 3 files ?

**Comment by JeffAbrahamson** [comment]
> Last part of 530. Need some fix

You probably don't want to create PRs whose first line says "please don't look at me".  If it needs fixing, just mark it as a draft.

**Pull request closed without merging**
