### PR TITLE
Add test that checks for missing migrations

### PR DESCRIPTION
**Pull request by Shriukan33**
We sometimes forget to add migrations to commits, this test will check for that.

### CODE REVIEW

**Comment by Shriukan33** [comment]
(the failing test is confirmation that it works ! \ o / )

**Comment by JeffAbrahamson** [comment]
This won't reject a commit.

It also doesn't pass its own test. ;-)

**Comment by Shriukan33** [comment]
the test fails because on this branch, the migration is missing, so this is actually a passing test if you ask me :) I'd be worried if the test showed green while a migration is indeed missing ! 

And no, it doesn't reject the commit, but at least you know before merging that a migration file is missing.

**Comment by Shriukan33** [comment]
@JeffAbrahamson  Can I merge this non-passing-tests-but-it's-actually-a-good-thing ? :)

**Review by JeffAbrahamson — APPROVED** [review]
LGTM.

**Pull request merged**
