### PR TITLE
Benja compress bundle static 362

### PR DESCRIPTION
**Pull request by Shriukan33**
This PR introduces django_compressor.

This lib compresses linked and inline JavaScript or CSS into a single cached file.

The generated file has a name that depends on its content, so it forces cache to update when its content changes.

image

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
* Have you tested on beta?
* Have you compared to any other technique?
* Have you compared performance (TTFB, TTFCP, TTFMP, etc.), lighthouse?

**Comment by Shriukan33** [comment]
> * Have you tested on beta?
> 
>     * Have you compared to any other technique?
> 
>     * Have you compared performance (TTFB, TTFCP, TTFMP, etc.), lighthouse?

* Tested on beta, it's currently deployed. 
* I've looked at https://github.com/MicroPyramid/django-webpacker , https://github.com/django-webpack/django-webpack-loader, https://github.com/sdcooke/django_bundles : The two first rely on npm, the last is deprecated. On top of that, this lib is actually easy to add in the project and to use, and the last update is recent (august). 
* I didn't, so here it goes, on beta : 

# JS 

On the https://beta.mobilitains.fr/tb/admin/t/new/ , as it brings several js files and extends base_mobilitain.html, with CTRL + F5 : 
image

In comparison, on mobilitains.fr (which is master) : 
image

# CSS
beta : 
image

prod : 
image

Page load time : 
beta : 
image

prod : 
image

# Landing page (incognito mode)

https://mobilitains.fr/ : 
image

https://beta.mobilitains.fr/ : 
image


These results look pretty good to me !

**Review by JeffAbrahamson — APPROVED** [review]
LGTM.

**Comment by JeffAbrahamson** [comment]
> These results look pretty good to me !

Thanks.  (They'd look even better if you were consistent in your ordering of prod and beta... ;-)

**Pull request merged**
