### PR TITLE
Apply Simon's suggestions on Mobilito design

### LINKED ISSUE #892: Change color scheme and buttons look
We should give a try to Simon's suggestion, as described in #889

### PR DESCRIPTION
**Pull request by Shriukan33**
Closes #892

image

image

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
@Shriukan33 - No longer cleanly rebases to master.

**Review by JeffAbrahamson — APPROVED** [review]
LGTM.

Suggestion: the commit message doesn't say what you did, only why you did it.  Perhaps you could enumerate the conversation with Simon in your commit message so that future generations can understand what you were changing and why.

**Comment by Shriukan33** [comment]
> LGTM.
> 
> Suggestion: the commit message doesn't say what you did, only why you did it. Perhaps you could enumerate the conversation with Simon in your commit message so that future generations can understand what you were changing and why.

Added reference to discussion, as the commit format wasn't fit to describe its content in a concise way.

**Comment by JeffAbrahamson** [comment]
> > LGTM.
> > Suggestion: the commit message doesn't say what you did, only why you did it. Perhaps you could enumerate the conversation with Simon in your commit message so that future generations can understand what you were changing and why.
> 
> Added reference to discussion, as the commit format wasn't fit to describe its content in a concise way.

In the year 2023, how will anyone reading the code know what your discussion with Simon was about?

I don't see it explained here:
```
commit 35328842df552a0338ea6eb3d9560ae5383f8c24 (HEAD -> master, origin/master)
Author: Benjamin Mourgues <benjamin@mobilitains.fr>
Date:   Wed Aug 17 17:08:28 2022 +0200

    Apply Simon's suggestions on Mobilito design
    
    Details of the conversation leading to this change
    are in discussion #889
    
    Closes #892

commit 549b712ab144ceaae2181811e54e9d1295bca5fa
```
and I don't see it explained in `git diff 549b712ab..3532884`, which makes clear what you did, but not why.

The issue is on github and is outside git.  Just like with google docs and other such things, either we commit into git or we are stating that future generations will have no need of it.

**Pull request merged**
