### PR TITLE
New index page

### PR DESCRIPTION
**Pull request by Shriukan33**
Based on gaelle's work : 
[20211208-index.pdf](https://github.com/transport-nantes/tn_web/files/7676652/20211208-index.pdf)

:warning:  Branch based on deployed branch nuke-banner ! 

Not ready to merge, need to have pages Agir and Petite Mobilité to complete the navbar. 

Agir page has its own PR : https://github.com/transport-nantes/tn_web/pull/324

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Do those images need to be so heavy?

```
╭╴ ((95f30aa...) %) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ identify asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg
asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg JPEG 2048x2048 2048x2048+0+0 8-bit sRGB 1.13952MiB 0.000u 0:00.000
╭╴ ((95f30aa...) %) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ identify topicblog/static/topicblog/banner_image.jpg
topicblog/static/topicblog/banner_image.jpg JPEG 6016x4000 6016x4000+0+0 8-bit sRGB 1.36179MiB 0.000u 0:00.000
╭╴ ((95f30aa...) %) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ ls -sh asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg
1.2M asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg
╭╴ ((95f30aa...) %) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ ls -sh topicblog/static/topicblog/banner_image.jpg
1.4M topicblog/static/topicblog/banner_image.jpg
╭╴ ((95f30aa...) %) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ 

```

**Comment by JeffAbrahamson** [comment]
Tests fail.

**Comment by JeffAbrahamson** [comment]
Why does the landing page need to not be a TBItem?

**Comment by JeffAbrahamson** [comment]
I'd suggest making the templatetag changes separately.  I.e., one change to update the volunteer templatetag.  One change to update the qui-sommes-nous templatetag.  Etc.

At that point, the top of the page should really be a TBItem, I think.

**Comment by Shriukan33** [comment]
> Why does the landing page need to not be a TBItem?

It's been discussed that for now, the landing page should be static and changed when needed. 
The new landing page doesn't fit inside current version of TBv2 in its possibilities, so I created a template and a view that make the Landing page independent from TBItems. 

It allows us to have more flexibility regarding the landing page, while keeping the fast production of TBv2 for content.

**Comment by Shriukan33** [comment]
> 

Will split commit to reflect the changes 

What do you mean by the top of the page should be a TBI ? The whole banner / text ?

**Comment by Shriukan33** [comment]
> Do those images need to be so heavy?
> 
> ```
> ╭╴ ((95f30aa...) %) [virt]╶╮
> ╰ jeff@birdsong:transport_nantes $ identify asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg
> asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg JPEG 2048x2048 2048x2048+0+0 8-bit sRGB 1.13952MiB 0.000u 0:00.000
> ╭╴ ((95f30aa...) %) [virt]╶╮
> ╰ jeff@birdsong:transport_nantes $ identify topicblog/static/topicblog/banner_image.jpg
> topicblog/static/topicblog/banner_image.jpg JPEG 6016x4000 6016x4000+0+0 8-bit sRGB 1.36179MiB 0.000u 0:00.000
> ╭╴ ((95f30aa...) %) [virt]╶╮
> ╰ jeff@birdsong:transport_nantes $ ls -sh asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg
> 1.2M asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg
> ╭╴ ((95f30aa...) %) [virt]╶╮
> ╰ jeff@birdsong:transport_nantes $ ls -sh topicblog/static/topicblog/banner_image.jpg
> 1.4M topicblog/static/topicblog/banner_image.jpg
> ╭╴ ((95f30aa...) %) [virt]╶╮
> ╰ jeff@birdsong:transport_nantes $ 
> ```

Will see to have a lighter version of it, do you know efficient ways to compress without much loss ?

**Comment by JeffAbrahamson** [comment]
> > I'd suggest making the templatetag changes separately.  I.e., one change to update the volunteer templatetag.  One change to update the qui-sommes-nous templatetag.  Etc.
> > At that point, the top of the page should really be a TBItem, I think.
> 
> Will split commit to reflect the changes
> 
> What do you mean by the top of the page should be a TBI ? The whole banner / text ?

The part in the `app_content` block.  I.e., above
```
    </div>
     <div class="background-ad-hoc-blue">
          <div class="d-flex flex-column p-4 p-xl-5">
               {% show_projects %}
               {% show_mailing_list %}
               {% show_qui_sommes_nous %}
          </div>
     </div>

     {% show_donate %}
     <div id="volunteer">
          {% show_volunteer %}
     </div>

```

**Comment by JeffAbrahamson** [comment]
> > Do those images need to be so heavy?
> > ```
> > ╭╴ ((95f30aa...) %) [virt]╶╮
> > ╰ jeff@birdsong:transport_nantes $ identify asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg
> > asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg JPEG 2048x2048 2048x2048+0+0 8-bit sRGB 1.13952MiB 0.000u 0:00.000
> > ╭╴ ((95f30aa...) %) [virt]╶╮
> > ╰ jeff@birdsong:transport_nantes $ identify topicblog/static/topicblog/banner_image.jpg
> > topicblog/static/topicblog/banner_image.jpg JPEG 6016x4000 6016x4000+0+0 8-bit sRGB 1.36179MiB 0.000u 0:00.000
> > ╭╴ ((95f30aa...) %) [virt]╶╮
> > ╰ jeff@birdsong:transport_nantes $ ls -sh asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg
> > 1.2M asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg
> > ╭╴ ((95f30aa...) %) [virt]╶╮
> > ╰ jeff@birdsong:transport_nantes $ ls -sh topicblog/static/topicblog/banner_image.jpg
> > 1.4M topicblog/static/topicblog/banner_image.jpg
> > ╭╴ ((95f30aa...) %) [virt]╶╮
> > ╰ jeff@birdsong:transport_nantes $ 
> > ```
> 
> Will see to have a lighter version of it, do you know efficient ways to compress without much loss ?

`convert`, from imagemagick, available from your local apt repo.

**Comment by JeffAbrahamson** [comment]
The more I think about this, the more I think we need to delete this branch.  The asso_tn mechanism is legacy and meant only for items where we need outside tracability or where we really can't do otherwise.

Everything else should be subject to really strong push-back: how can we get 80% or 90% of what we want with TBv2 and so get it with 10% of the effort.  Once a page's content is designed, it's 10-15 minutes in TBv2 or several hours to days with asso_tn and a custom design and fiddling to get responsiveness right on something that 99 times out of a 100 was designed _first_ for a large screen.

As discussed during the meeting Tuesday, it's really intentional that TBv2 limits design choices.  We need to focus on content, not on design.

Remember the old Velopolitain page with the fancy images to the side and the text next to them?  And we were about to implement that, and then did what's there  now, which is just headlines.  And it works just fine.

I've implemented the bulk of what Gaelle requested for the index with a TBItem.  It took 10 minutes.  The part we don't have we'll live without until we can make a case that it will bring in a 5-10 new members to pay for itself. ;-)

**Comment by jyoost** [comment]
> Do those images need to be so heavy?
> 
> ```
> ╭╴ ((95f30aa...) %) [virt]╶╮
> ╰ jeff@birdsong:transport_nantes $ identify asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg
> asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg JPEG 2048x2048 2048x2048+0+0 8-bit sRGB 1.13952MiB 0.000u 0:00.000
> ╭╴ ((95f30aa...) %) [virt]╶╮
> ╰ jeff@birdsong:transport_nantes $ identify topicblog/static/topicblog/banner_image.jpg
> topicblog/static/topicblog/banner_image.jpg JPEG 6016x4000 6016x4000+0+0 8-bit sRGB 1.36179MiB 0.000u 0:00.000
> ╭╴ ((95f30aa...) %) [virt]╶╮
> ╰ jeff@birdsong:transport_nantes $ ls -sh asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg
> 1.2M asso_tn/static/asso_tn/qui-sommes-nous/quisommesnous.jpg
> ╭╴ ((95f30aa...) %) [virt]╶╮
> ╰ jeff@birdsong:transport_nantes $ ls -sh topicblog/static/topicblog/banner_image.jpg
> 1.4M topicblog/static/topicblog/banner_image.jpg
> ╭╴ ((95f30aa...) %) [virt]╶╮
> ╰ jeff@birdsong:transport_nantes $ 
> ```

I used imagemagick to redo images that needed to be smaller accords the board.  The easiest way to assure that images can be used any size in the future is versatileimagefield.

This lets you resize images on-the-fly with caching.

By putting a reference in a template.

**Pull request closed without merging**
