### PR TITLE
Add GET handling for TBESend

### PR DESCRIPTION
**Pull request by Shriukan33**
Creates a form in which you can select an existing mailing list to send you TBEmail to.
POST isn't handled yet in this commit.

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Maybe that commit comment is a bit light and inaccurate for the commit content?

**Comment by JeffAbrahamson** [comment]
LGTM but please do amend the commit message so that it explains what you did.

**Comment by Shriukan33** [comment]
Ran tests against this branch, pass OK on local : 
image

@mcmikashi any idea why it would fail here ?

**Comment by JeffAbrahamson** [comment]
This is maybe a bit suspicious:

```
╭╴ ((45bc755...) $%) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ grep mailing_list_mailinglist mailing_list/migrations/*
grep: mailing_list/migrations/__pycache__: Is a directory
╭╴ ((45bc755...) $%) [virt]╶╮
╰ 2, jeff@birdsong:transport_nantes $ 
```

**Comment by JeffAbrahamson** [comment]
The model changed on 2 March.  I'm not sure why that should matter, it was just adding permissions:

```commit 0cc5927b72b8bbf932f1500a2f01ba4ab216b7f7
Author: Benjamin Mourgues <benjamin@mobilitains.fr>
Date:   Wed Mar 2 11:24:58 2022 +0100

    Add tests to Mailing list.
    
    Writing the tests has shown some bugs, the fixes are included.

 transport_nantes/mailing_list/models.py | 13 +++++++++----
 1 file changed, 9 insertions(+), 4 deletions(-)
```

**Comment by Shriukan33** [comment]
I think my Linter gave me a clue : 
image

Modules and classes are usually green for me, however mailing_list.templatetags, imported in tn_links, is written in white while being valid code. 
Why is that ? 

I compared the asso_tn's templatetags folder with mailing_list's, and the only noticeable difference I can see is that mailing_list doesn't have a `__init__.py` file, which is often used to mark a folder as a module.

Because the error mentions a module import error, maybe adding a  `__init__.py`to mailing_list's templatetags folder could fix this issue ? Will make a branch to try that.

**Pull request merged**
