### PR TITLE
Add simple makefile to codify dev workflow

### PR DESCRIPTION
**Pull request by JeffAbrahamson**
Part of #303.

### CODE REVIEW

**Comment by Shriukan33** [comment]
If I understand this correctly, it will run migrate & test after installing dependencies in the deploy so we see the tests running each deploy, is that right ?
What's the point of run though ?

**Comment by JeffAbrahamson** [comment]
Type `make test` or `make run`.

**Comment by Shriukan33** [comment]
> Type `make test` or `make run`.

Where ?

**Comment by JeffAbrahamson** [comment]
```
╭╴ (master $%=) [virt]╶╮
╰ 2, jeff@birdsong:transport_nantes $ make test
. ../venv/bin/activate && python manage.py migrate && python manage.py test
Operations to perform:
  Apply all migrations: admin, auth, authentication, captcha, clickcollect, contenttypes, geoplan, mailing_list, sessions, stripe_app, surveys, topicblog
Running migrations:
  No migrations to apply.
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...--
.........--
..--
......--
--
.--
.--
.--
......--
...........
----------------------------------------------------------------------
Ran 40 tests in 6.461s

OK
Destroying test database for alias 'default'...
╭╴ (master $%=) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ make run
. ../venv/bin/activate && python manage.py migrate && python manage.py runserver
Operations to perform:
  Apply all migrations: admin, auth, authentication, captcha, clickcollect, contenttypes, geoplan, mailing_list, sessions, stripe_app, surveys, topicblog
Running migrations:
  No migrations to apply.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
December 02, 2021 - 02:51:52
Django version 3.2.5, using settings 'transport_nantes.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
--
```

**Pull request merged**
