### PR TITLE
Changes to make django-cms work, including

### PR DESCRIPTION
**Pull request by jyoost**
the djangocms_blog, available at /cms/blog
a copy of my dev DB included in
db.sqlite3.dev @Shriukan33

### CODE REVIEW

**Comment by Shriukan33** [comment]
Thanks for the help, will look at that tomorrow :)
Cheers, happy holidays!

**Comment by Shriukan33** [comment]
```
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/benja/Documents/GitHub/tn_web/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/benja/Documents/GitHub/tn_web/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "/home/benja/Documents/GitHub/tn_web/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/benja/Documents/GitHub/tn_web/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "/home/benja/Documents/GitHub/tn_web/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/benja/Documents/GitHub/tn_web/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/benja/Documents/GitHub/tn_web/venv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/benja/Documents/GitHub/tn_web/venv/lib/python3.8/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'aldryn_apphooks_config'
```

I've done the pip install -r requirements.txt and used your dev db. 
Is there anything more to do ?

**Comment by jyoost** [comment]
try  pip install aldryn-apphooks-config==0.6.0 

@Shriukan33

**Comment by JeffAbrahamson** [comment]
Hey, can you guys discuss this in the issue and not in a PR, since this isn't currently a merge candidate?

Thanks.  I'm closing just for that, I'll leave you to continue in the issue.

**Pull request closed without merging**
