### PR TITLE
Add filter on newspaper name

### PR DESCRIPTION
**Pull request by mcmikashi**
The first and second commit is there for no merging conflic.
On the last commit i add link on newspaper that open on new tab and filter the table.

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
LGTM.

At some point, could you update the button styles to conform to our [style guide](https://www.mobilitains.fr/tb/t/guide-visuel-mobilitains/)?  There's CSS support for it.  If it's unclear or the CSS is not right, just ask.

The style guide page will move, it wasn't supposed to be a TBItem.  Long story.

**Comment by Shriukan33** [comment]
I don't want to put words in Jeff's mouth, but I think he meant these buttons : 
image
image

**Comment by JeffAbrahamson** [comment]
LGTM.

There are some visual quibbles, like the table header not extending over the last column, but they can be addressed later.

More important is that it's not responsive.  The reason that the world abandoned HTML tables in favour of CSS tables is that HTML tables largely break as screen size changes.

**Comment by JeffAbrahamson** [comment]
(Oh, I was looking at `origin/press-mickael-474`...)

**Pull request merged**
